package com.bt.om.entity;

import java.util.Date;

public class AdActivityArea extends ID{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_activity_area.id
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_activity_area.activity_id
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    private Integer activityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_activity_area.province
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    private Integer province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_activity_area.city
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    private Integer city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_activity_area.region
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    private Integer region;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_activity_area.street
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    private Integer street;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_activity_area.create_time
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_activity_area.update_time
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_activity_area.id
     *
     * @return the value of ad_activity_area.id
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_activity_area.id
     *
     * @param id the value for ad_activity_area.id
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_activity_area.activity_id
     *
     * @return the value of ad_activity_area.activity_id
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    public Integer getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_activity_area.activity_id
     *
     * @param activityId the value for ad_activity_area.activity_id
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_activity_area.province
     *
     * @return the value of ad_activity_area.province
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    public Integer getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_activity_area.province
     *
     * @param province the value for ad_activity_area.province
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    public void setProvince(Integer province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_activity_area.city
     *
     * @return the value of ad_activity_area.city
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    public Integer getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_activity_area.city
     *
     * @param city the value for ad_activity_area.city
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    public void setCity(Integer city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_activity_area.region
     *
     * @return the value of ad_activity_area.region
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    public Integer getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_activity_area.region
     *
     * @param region the value for ad_activity_area.region
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    public void setRegion(Integer region) {
        this.region = region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_activity_area.street
     *
     * @return the value of ad_activity_area.street
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    public Integer getStreet() {
        return street;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_activity_area.street
     *
     * @param street the value for ad_activity_area.street
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    public void setStreet(Integer street) {
        this.street = street;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_activity_area.create_time
     *
     * @return the value of ad_activity_area.create_time
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_activity_area.create_time
     *
     * @param createTime the value for ad_activity_area.create_time
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_activity_area.update_time
     *
     * @return the value of ad_activity_area.update_time
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_activity_area.update_time
     *
     * @param updateTime the value for ad_activity_area.update_time
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}