package com.bt.om.entity;

import java.util.Date;

public class AdActivity extends ID{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_activity.id
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_activity.activity_name
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    private String activityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_activity.start_time
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_activity.end_time
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_activity.status
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_activity.user_id
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_activity.create_time
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_activity.update_time
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    private Date updateTime;

    private Integer customerTypeId;
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_activity.id
     *
     * @return the value of ad_activity.id
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    private Integer assessorId;
    
    private String samplePicUrl;
    
    private String createTimeStr;
    
    private String updateTimeStr;
    
    private String upTaskTime;
    
    private String upMonitorTaskTime;
    
    private String durationMonitorTaskTime;
    
    private String downMonitorTaskTime;
    
    private String zhuijiaMonitorTaskTime;
    
    public String getCreateTimeStr() {
		return createTimeStr;
	}

	public void setCreateTimeStr(String createTimeStr) {
		this.createTimeStr = createTimeStr;
	}

	public String getUpdateTimeStr() {
		return updateTimeStr;
	}

	public void setUpdateTimeStr(String updateTimeStr) {
		this.updateTimeStr = updateTimeStr;
	}

	public String getSamplePicUrl() {
		return samplePicUrl;
	}

	public void setSamplePicUrl(String samplePicUrl) {
		this.samplePicUrl = samplePicUrl;
	}

	public Integer getAssessorId() {
		return assessorId;
	}

	public void setAssessorId(Integer assessorId) {
		this.assessorId = assessorId;
	}

	public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_activity.id
     *
     * @param id the value for ad_activity.id
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_activity.activity_name
     *
     * @return the value of ad_activity.activity_name
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    public String getActivityName() {
        return activityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_activity.activity_name
     *
     * @param activityName the value for ad_activity.activity_name
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    public void setActivityName(String activityName) {
        this.activityName = activityName == null ? null : activityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_activity.start_time
     *
     * @return the value of ad_activity.start_time
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_activity.start_time
     *
     * @param startTime the value for ad_activity.start_time
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_activity.end_time
     *
     * @return the value of ad_activity.end_time
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_activity.end_time
     *
     * @param endTime the value for ad_activity.end_time
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_activity.status
     *
     * @return the value of ad_activity.status
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_activity.status
     *
     * @param status the value for ad_activity.status
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_activity.user_id
     *
     * @return the value of ad_activity.user_id
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_activity.user_id
     *
     * @param userId the value for ad_activity.user_id
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_activity.create_time
     *
     * @return the value of ad_activity.create_time
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_activity.create_time
     *
     * @param createTime the value for ad_activity.create_time
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_activity.update_time
     *
     * @return the value of ad_activity.update_time
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_activity.update_time
     *
     * @param updateTime the value for ad_activity.update_time
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
    
    public Integer getCustomerTypeId() {
		return customerTypeId;
	}
    
    public void setCustomerTypeId(Integer customerTypeId) {
		this.customerTypeId = customerTypeId;
	}

	public String getUpTaskTime() {
		return upTaskTime;
	}

	public void setUpTaskTime(String upTaskTime) {
		this.upTaskTime = upTaskTime;
	}

	public String getUpMonitorTaskTime() {
		return upMonitorTaskTime;
	}

	public void setUpMonitorTaskTime(String upMonitorTaskTime) {
		this.upMonitorTaskTime = upMonitorTaskTime;
	}

	public String getDurationMonitorTaskTime() {
		return durationMonitorTaskTime;
	}

	public void setDurationMonitorTaskTime(String durationMonitorTaskTime) {
		this.durationMonitorTaskTime = durationMonitorTaskTime;
	}

	public String getDownMonitorTaskTime() {
		return downMonitorTaskTime;
	}

	public void setDownMonitorTaskTime(String downMonitorTaskTime) {
		this.downMonitorTaskTime = downMonitorTaskTime;
	}
    
	public String getZhuijiaMonitorTaskTime() {
		return zhuijiaMonitorTaskTime;
	}
	
	public void setZhuijiaMonitorTaskTime(String zhuijiaMonitorTaskTime) {
		this.zhuijiaMonitorTaskTime = zhuijiaMonitorTaskTime;
	}
}