package com.bt.om.entity;

import java.util.Date;

public class AdActivityAdseat extends ID{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_activity_adseat.id
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_activity_adseat.activity_id
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    private Integer activityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_activity_adseat.media_id
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    private Integer mediaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_activity_adseat.ad_seat_id
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    private Integer adSeatId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_activity_adseat.brand
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    private String brand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_activity_adseat.monitor_start
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    private Date monitorStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_activity_adseat.monitor_end
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    private Date monitorEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_activity_adseat.monitor_count
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    private Integer monitorCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_activity_adseat.up_monitor
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    private Integer upMonitor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_activity_adseat.down_monitor
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    private Integer downMonitor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_activity_adseat.duration_monitor
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    private Integer durationMonitor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_activity_adseat.sample_pic_url
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    private String samplePicUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_activity_adseat.task_create
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    private Integer taskCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_activity_adseat.create_time
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_activity_adseat.update_time
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_activity_adseat.id
     *
     * @return the value of ad_activity_adseat.id
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_activity_adseat.id
     *
     * @param id the value for ad_activity_adseat.id
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_activity_adseat.activity_id
     *
     * @return the value of ad_activity_adseat.activity_id
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    public Integer getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_activity_adseat.activity_id
     *
     * @param activityId the value for ad_activity_adseat.activity_id
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_activity_adseat.media_id
     *
     * @return the value of ad_activity_adseat.media_id
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    public Integer getMediaId() {
        return mediaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_activity_adseat.media_id
     *
     * @param mediaId the value for ad_activity_adseat.media_id
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    public void setMediaId(Integer mediaId) {
        this.mediaId = mediaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_activity_adseat.ad_seat_id
     *
     * @return the value of ad_activity_adseat.ad_seat_id
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    public Integer getAdSeatId() {
        return adSeatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_activity_adseat.ad_seat_id
     *
     * @param adSeatId the value for ad_activity_adseat.ad_seat_id
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    public void setAdSeatId(Integer adSeatId) {
        this.adSeatId = adSeatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_activity_adseat.brand
     *
     * @return the value of ad_activity_adseat.brand
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_activity_adseat.brand
     *
     * @param brand the value for ad_activity_adseat.brand
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    public void setBrand(String brand) {
        this.brand = brand == null ? null : brand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_activity_adseat.monitor_start
     *
     * @return the value of ad_activity_adseat.monitor_start
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    public Date getMonitorStart() {
        return monitorStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_activity_adseat.monitor_start
     *
     * @param monitorStart the value for ad_activity_adseat.monitor_start
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    public void setMonitorStart(Date monitorStart) {
        this.monitorStart = monitorStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_activity_adseat.monitor_end
     *
     * @return the value of ad_activity_adseat.monitor_end
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    public Date getMonitorEnd() {
        return monitorEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_activity_adseat.monitor_end
     *
     * @param monitorEnd the value for ad_activity_adseat.monitor_end
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    public void setMonitorEnd(Date monitorEnd) {
        this.monitorEnd = monitorEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_activity_adseat.monitor_count
     *
     * @return the value of ad_activity_adseat.monitor_count
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    public Integer getMonitorCount() {
        return monitorCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_activity_adseat.monitor_count
     *
     * @param monitorCount the value for ad_activity_adseat.monitor_count
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    public void setMonitorCount(Integer monitorCount) {
        this.monitorCount = monitorCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_activity_adseat.up_monitor
     *
     * @return the value of ad_activity_adseat.up_monitor
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    public Integer getUpMonitor() {
        return upMonitor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_activity_adseat.up_monitor
     *
     * @param upMonitor the value for ad_activity_adseat.up_monitor
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    public void setUpMonitor(Integer upMonitor) {
        this.upMonitor = upMonitor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_activity_adseat.down_monitor
     *
     * @return the value of ad_activity_adseat.down_monitor
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    public Integer getDownMonitor() {
        return downMonitor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_activity_adseat.down_monitor
     *
     * @param downMonitor the value for ad_activity_adseat.down_monitor
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    public void setDownMonitor(Integer downMonitor) {
        this.downMonitor = downMonitor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_activity_adseat.duration_monitor
     *
     * @return the value of ad_activity_adseat.duration_monitor
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    public Integer getDurationMonitor() {
        return durationMonitor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_activity_adseat.duration_monitor
     *
     * @param durationMonitor the value for ad_activity_adseat.duration_monitor
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    public void setDurationMonitor(Integer durationMonitor) {
        this.durationMonitor = durationMonitor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_activity_adseat.sample_pic_url
     *
     * @return the value of ad_activity_adseat.sample_pic_url
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    public String getSamplePicUrl() {
        return samplePicUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_activity_adseat.sample_pic_url
     *
     * @param samplePicUrl the value for ad_activity_adseat.sample_pic_url
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    public void setSamplePicUrl(String samplePicUrl) {
        this.samplePicUrl = samplePicUrl == null ? null : samplePicUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_activity_adseat.task_create
     *
     * @return the value of ad_activity_adseat.task_create
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    public Integer getTaskCreate() {
        return taskCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_activity_adseat.task_create
     *
     * @param taskCreate the value for ad_activity_adseat.task_create
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    public void setTaskCreate(Integer taskCreate) {
        this.taskCreate = taskCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_activity_adseat.create_time
     *
     * @return the value of ad_activity_adseat.create_time
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_activity_adseat.create_time
     *
     * @param createTime the value for ad_activity_adseat.create_time
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_activity_adseat.update_time
     *
     * @return the value of ad_activity_adseat.update_time
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_activity_adseat.update_time
     *
     * @param updateTime the value for ad_activity_adseat.update_time
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    private Integer upMonitorLastDays;
    private Integer durationMonitorLastDays;
    private Integer downMonitorLastDays;

    public Integer getUpMonitorLastDays() {
        return upMonitorLastDays;
    }

    public void setUpMonitorLastDays(Integer upMonitorLastDays) {
        this.upMonitorLastDays = upMonitorLastDays;
    }

    public Integer getDurationMonitorLastDays() {
        return durationMonitorLastDays;
    }

    public void setDurationMonitorLastDays(Integer durationMonitorLastDays) {
        this.durationMonitorLastDays = durationMonitorLastDays;
    }

    public Integer getDownMonitorLastDays() {
        return downMonitorLastDays;
    }

    public void setDownMonitorLastDays(Integer downMonitorLastDays) {
        this.downMonitorLastDays = downMonitorLastDays;
    }
}