package com.bt.om.entity;

import java.util.Date;

public class AdJiucuoTask extends ID {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_jiucuo_task.id
     *
     * @mbggenerated Sun Jan 21 14:46:36 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_jiucuo_task.activity_id
     *
     * @mbggenerated Sun Jan 21 14:46:36 CST 2018
     */
    private Integer activityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_jiucuo_task.ad_seat_id
     *
     * @mbggenerated Sun Jan 21 14:46:36 CST 2018
     */
    private Integer adSeatId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_jiucuo_task.submit_time
     *
     * @mbggenerated Sun Jan 21 14:46:36 CST 2018
     */
    private Date submitTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_jiucuo_task.user_id
     *
     * @mbggenerated Sun Jan 21 14:46:36 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_jiucuo_task.status
     *
     * @mbggenerated Sun Jan 21 14:46:36 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_jiucuo_task.create_time
     *
     * @mbggenerated Sun Jan 21 14:46:36 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_jiucuo_task.update_time
     *
     * @mbggenerated Sun Jan 21 14:46:36 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_jiucuo_task.id
     *
     * @return the value of ad_jiucuo_task.id
     *
     * @mbggenerated Sun Jan 21 14:46:36 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_jiucuo_task.id
     *
     * @param id the value for ad_jiucuo_task.id
     *
     * @mbggenerated Sun Jan 21 14:46:36 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_jiucuo_task.activity_id
     *
     * @return the value of ad_jiucuo_task.activity_id
     *
     * @mbggenerated Sun Jan 21 14:46:36 CST 2018
     */
    public Integer getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_jiucuo_task.activity_id
     *
     * @param activityId the value for ad_jiucuo_task.activity_id
     *
     * @mbggenerated Sun Jan 21 14:46:36 CST 2018
     */
    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_jiucuo_task.ad_seat_id
     *
     * @return the value of ad_jiucuo_task.ad_seat_id
     *
     * @mbggenerated Sun Jan 21 14:46:36 CST 2018
     */
    public Integer getAdSeatId() {
        return adSeatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_jiucuo_task.ad_seat_id
     *
     * @param adSeatId the value for ad_jiucuo_task.ad_seat_id
     *
     * @mbggenerated Sun Jan 21 14:46:36 CST 2018
     */
    public void setAdSeatId(Integer adSeatId) {
        this.adSeatId = adSeatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_jiucuo_task.submit_time
     *
     * @return the value of ad_jiucuo_task.submit_time
     *
     * @mbggenerated Sun Jan 21 14:46:36 CST 2018
     */
    public Date getSubmitTime() {
        return submitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_jiucuo_task.submit_time
     *
     * @param submitTime the value for ad_jiucuo_task.submit_time
     *
     * @mbggenerated Sun Jan 21 14:46:36 CST 2018
     */
    public void setSubmitTime(Date submitTime) {
        this.submitTime = submitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_jiucuo_task.user_id
     *
     * @return the value of ad_jiucuo_task.user_id
     *
     * @mbggenerated Sun Jan 21 14:46:36 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_jiucuo_task.user_id
     *
     * @param userId the value for ad_jiucuo_task.user_id
     *
     * @mbggenerated Sun Jan 21 14:46:36 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_jiucuo_task.status
     *
     * @return the value of ad_jiucuo_task.status
     *
     * @mbggenerated Sun Jan 21 14:46:36 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_jiucuo_task.status
     *
     * @param status the value for ad_jiucuo_task.status
     *
     * @mbggenerated Sun Jan 21 14:46:36 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_jiucuo_task.create_time
     *
     * @return the value of ad_jiucuo_task.create_time
     *
     * @mbggenerated Sun Jan 21 14:46:36 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_jiucuo_task.create_time
     *
     * @param createTime the value for ad_jiucuo_task.create_time
     *
     * @mbggenerated Sun Jan 21 14:46:36 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_jiucuo_task.update_time
     *
     * @return the value of ad_jiucuo_task.update_time
     *
     * @mbggenerated Sun Jan 21 14:46:36 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_jiucuo_task.update_time
     *
     * @param updateTime the value for ad_jiucuo_task.update_time
     *
     * @mbggenerated Sun Jan 21 14:46:36 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    private String reason;
    private Integer problemStatus;
    private Integer subCreated;

    public Integer getSubCreated() {
        return subCreated;
    }

    public void setSubCreated(Integer subCreated) {
        this.subCreated = subCreated;
    }

    public Integer getProblemStatus() {
        return problemStatus;
    }

    public void setProblemStatus(Integer problemStatus) {
        this.problemStatus = problemStatus;
    }

    public String getReason() {
        return reason;
    }

    public void setReason(String reason) {
        this.reason = reason;
    }
}