package com.bt.om.entity;

import java.util.Date;

public class AdJiucuoTaskFeedback {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_jiucuo_task_feedback.id
     *
     * @mbggenerated Sun Jan 21 14:59:02 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_jiucuo_task_feedback.jiucuo_task_id
     *
     * @mbggenerated Sun Jan 21 14:59:02 CST 2018
     */
    private Integer jiucuoTaskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_jiucuo_task_feedback.pic_url1
     *
     * @mbggenerated Sun Jan 21 14:59:02 CST 2018
     */
    private String picUrl1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_jiucuo_task_feedback.pic_url2
     *
     * @mbggenerated Sun Jan 21 14:59:02 CST 2018
     */
    private String picUrl2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_jiucuo_task_feedback.pic_url3
     *
     * @mbggenerated Sun Jan 21 14:59:02 CST 2018
     */
    private String picUrl3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_jiucuo_task_feedback.pic_url4
     *
     * @mbggenerated Sun Jan 21 14:59:02 CST 2018
     */
    private String picUrl4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_jiucuo_task_feedback.problem
     *
     * @mbggenerated Sun Jan 21 14:59:02 CST 2018
     */
    private String problem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_jiucuo_task_feedback.problem_other
     *
     * @mbggenerated Sun Jan 21 14:59:02 CST 2018
     */
    private String problemOther;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_jiucuo_task_feedback.lon
     *
     * @mbggenerated Sun Jan 21 14:59:02 CST 2018
     */
    private Double lon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_jiucuo_task_feedback.lat
     *
     * @mbggenerated Sun Jan 21 14:59:02 CST 2018
     */
    private Double lat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_jiucuo_task_feedback.create_time
     *
     * @mbggenerated Sun Jan 21 14:59:02 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_jiucuo_task_feedback.update_time
     *
     * @mbggenerated Sun Jan 21 14:59:02 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_jiucuo_task_feedback.id
     *
     * @return the value of ad_jiucuo_task_feedback.id
     *
     * @mbggenerated Sun Jan 21 14:59:02 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_jiucuo_task_feedback.id
     *
     * @param id the value for ad_jiucuo_task_feedback.id
     *
     * @mbggenerated Sun Jan 21 14:59:02 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_jiucuo_task_feedback.jiucuo_task_id
     *
     * @return the value of ad_jiucuo_task_feedback.jiucuo_task_id
     *
     * @mbggenerated Sun Jan 21 14:59:02 CST 2018
     */
    public Integer getJiucuoTaskId() {
        return jiucuoTaskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_jiucuo_task_feedback.jiucuo_task_id
     *
     * @param jiucuoTaskId the value for ad_jiucuo_task_feedback.jiucuo_task_id
     *
     * @mbggenerated Sun Jan 21 14:59:02 CST 2018
     */
    public void setJiucuoTaskId(Integer jiucuoTaskId) {
        this.jiucuoTaskId = jiucuoTaskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_jiucuo_task_feedback.pic_url1
     *
     * @return the value of ad_jiucuo_task_feedback.pic_url1
     *
     * @mbggenerated Sun Jan 21 14:59:02 CST 2018
     */
    public String getPicUrl1() {
        return picUrl1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_jiucuo_task_feedback.pic_url1
     *
     * @param picUrl1 the value for ad_jiucuo_task_feedback.pic_url1
     *
     * @mbggenerated Sun Jan 21 14:59:02 CST 2018
     */
    public void setPicUrl1(String picUrl1) {
        this.picUrl1 = picUrl1 == null ? null : picUrl1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_jiucuo_task_feedback.pic_url2
     *
     * @return the value of ad_jiucuo_task_feedback.pic_url2
     *
     * @mbggenerated Sun Jan 21 14:59:02 CST 2018
     */
    public String getPicUrl2() {
        return picUrl2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_jiucuo_task_feedback.pic_url2
     *
     * @param picUrl2 the value for ad_jiucuo_task_feedback.pic_url2
     *
     * @mbggenerated Sun Jan 21 14:59:02 CST 2018
     */
    public void setPicUrl2(String picUrl2) {
        this.picUrl2 = picUrl2 == null ? null : picUrl2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_jiucuo_task_feedback.pic_url3
     *
     * @return the value of ad_jiucuo_task_feedback.pic_url3
     *
     * @mbggenerated Sun Jan 21 14:59:02 CST 2018
     */
    public String getPicUrl3() {
        return picUrl3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_jiucuo_task_feedback.pic_url3
     *
     * @param picUrl3 the value for ad_jiucuo_task_feedback.pic_url3
     *
     * @mbggenerated Sun Jan 21 14:59:02 CST 2018
     */
    public void setPicUrl3(String picUrl3) {
        this.picUrl3 = picUrl3 == null ? null : picUrl3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_jiucuo_task_feedback.pic_url4
     *
     * @return the value of ad_jiucuo_task_feedback.pic_url4
     *
     * @mbggenerated Sun Jan 21 14:59:02 CST 2018
     */
    public String getPicUrl4() {
        return picUrl4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_jiucuo_task_feedback.pic_url4
     *
     * @param picUrl4 the value for ad_jiucuo_task_feedback.pic_url4
     *
     * @mbggenerated Sun Jan 21 14:59:02 CST 2018
     */
    public void setPicUrl4(String picUrl4) {
        this.picUrl4 = picUrl4 == null ? null : picUrl4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_jiucuo_task_feedback.problem
     *
     * @return the value of ad_jiucuo_task_feedback.problem
     *
     * @mbggenerated Sun Jan 21 14:59:02 CST 2018
     */
    public String getProblem() {
        return problem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_jiucuo_task_feedback.problem
     *
     * @param problem the value for ad_jiucuo_task_feedback.problem
     *
     * @mbggenerated Sun Jan 21 14:59:02 CST 2018
     */
    public void setProblem(String problem) {
        this.problem = problem == null ? null : problem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_jiucuo_task_feedback.problem_other
     *
     * @return the value of ad_jiucuo_task_feedback.problem_other
     *
     * @mbggenerated Sun Jan 21 14:59:02 CST 2018
     */
    public String getProblemOther() {
        return problemOther;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_jiucuo_task_feedback.problem_other
     *
     * @param problemOther the value for ad_jiucuo_task_feedback.problem_other
     *
     * @mbggenerated Sun Jan 21 14:59:02 CST 2018
     */
    public void setProblemOther(String problemOther) {
        this.problemOther = problemOther == null ? null : problemOther.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_jiucuo_task_feedback.lon
     *
     * @return the value of ad_jiucuo_task_feedback.lon
     *
     * @mbggenerated Sun Jan 21 14:59:02 CST 2018
     */
    public Double getLon() {
        return lon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_jiucuo_task_feedback.lon
     *
     * @param lon the value for ad_jiucuo_task_feedback.lon
     *
     * @mbggenerated Sun Jan 21 14:59:02 CST 2018
     */
    public void setLon(Double lon) {
        this.lon = lon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_jiucuo_task_feedback.lat
     *
     * @return the value of ad_jiucuo_task_feedback.lat
     *
     * @mbggenerated Sun Jan 21 14:59:02 CST 2018
     */
    public Double getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_jiucuo_task_feedback.lat
     *
     * @param lat the value for ad_jiucuo_task_feedback.lat
     *
     * @mbggenerated Sun Jan 21 14:59:02 CST 2018
     */
    public void setLat(Double lat) {
        this.lat = lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_jiucuo_task_feedback.create_time
     *
     * @return the value of ad_jiucuo_task_feedback.create_time
     *
     * @mbggenerated Sun Jan 21 14:59:02 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_jiucuo_task_feedback.create_time
     *
     * @param createTime the value for ad_jiucuo_task_feedback.create_time
     *
     * @mbggenerated Sun Jan 21 14:59:02 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_jiucuo_task_feedback.update_time
     *
     * @return the value of ad_jiucuo_task_feedback.update_time
     *
     * @mbggenerated Sun Jan 21 14:59:02 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_jiucuo_task_feedback.update_time
     *
     * @param updateTime the value for ad_jiucuo_task_feedback.update_time
     *
     * @mbggenerated Sun Jan 21 14:59:02 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    private Double seatLon;
    private Double seatLat;

    public Double getSeatLon() {
        return seatLon;
    }

    public void setSeatLon(Double seatLon) {
        this.seatLon = seatLon;
    }

    public Double getSeatLat() {
        return seatLat;
    }

    public void setSeatLat(Double seatLat) {
        this.seatLat = seatLat;
    }
}