package com.bt.om.entity;

import java.util.Date;

public class AdMediaType {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ad_media_type.id
	 * @mbg.generated  Tue Apr 24 18:10:17 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ad_media_type.name
	 * @mbg.generated  Tue Apr 24 18:10:17 CST 2018
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ad_media_type.parent_id
	 * @mbg.generated  Tue Apr 24 18:10:17 CST 2018
	 */
	private Integer parentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ad_media_type.media_type
	 * @mbg.generated  Tue Apr 24 18:10:17 CST 2018
	 */
	private Integer mediaType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ad_media_type.unique_key_need
	 * @mbg.generated  Tue Apr 24 18:10:17 CST 2018
	 */
	private Integer uniqueKeyNeed;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ad_media_type.status
	 * @mbg.generated  Tue Apr 24 18:10:17 CST 2018
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ad_media_type.create_time
	 * @mbg.generated  Tue Apr 24 18:10:17 CST 2018
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ad_media_type.update_time
	 * @mbg.generated  Tue Apr 24 18:10:17 CST 2018
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ad_media_type.id
	 * @return  the value of ad_media_type.id
	 * @mbg.generated  Tue Apr 24 18:10:17 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ad_media_type.id
	 * @param id  the value for ad_media_type.id
	 * @mbg.generated  Tue Apr 24 18:10:17 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ad_media_type.name
	 * @return  the value of ad_media_type.name
	 * @mbg.generated  Tue Apr 24 18:10:17 CST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ad_media_type.name
	 * @param name  the value for ad_media_type.name
	 * @mbg.generated  Tue Apr 24 18:10:17 CST 2018
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ad_media_type.parent_id
	 * @return  the value of ad_media_type.parent_id
	 * @mbg.generated  Tue Apr 24 18:10:17 CST 2018
	 */
	public Integer getParentId() {
		return parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ad_media_type.parent_id
	 * @param parentId  the value for ad_media_type.parent_id
	 * @mbg.generated  Tue Apr 24 18:10:17 CST 2018
	 */
	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ad_media_type.media_type
	 * @return  the value of ad_media_type.media_type
	 * @mbg.generated  Tue Apr 24 18:10:17 CST 2018
	 */
	public Integer getMediaType() {
		return mediaType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ad_media_type.media_type
	 * @param mediaType  the value for ad_media_type.media_type
	 * @mbg.generated  Tue Apr 24 18:10:17 CST 2018
	 */
	public void setMediaType(Integer mediaType) {
		this.mediaType = mediaType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ad_media_type.unique_key_need
	 * @return  the value of ad_media_type.unique_key_need
	 * @mbg.generated  Tue Apr 24 18:10:17 CST 2018
	 */
	public Integer getUniqueKeyNeed() {
		return uniqueKeyNeed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ad_media_type.unique_key_need
	 * @param uniqueKeyNeed  the value for ad_media_type.unique_key_need
	 * @mbg.generated  Tue Apr 24 18:10:17 CST 2018
	 */
	public void setUniqueKeyNeed(Integer uniqueKeyNeed) {
		this.uniqueKeyNeed = uniqueKeyNeed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ad_media_type.status
	 * @return  the value of ad_media_type.status
	 * @mbg.generated  Tue Apr 24 18:10:17 CST 2018
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ad_media_type.status
	 * @param status  the value for ad_media_type.status
	 * @mbg.generated  Tue Apr 24 18:10:17 CST 2018
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ad_media_type.create_time
	 * @return  the value of ad_media_type.create_time
	 * @mbg.generated  Tue Apr 24 18:10:17 CST 2018
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ad_media_type.create_time
	 * @param createTime  the value for ad_media_type.create_time
	 * @mbg.generated  Tue Apr 24 18:10:17 CST 2018
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ad_media_type.update_time
	 * @return  the value of ad_media_type.update_time
	 * @mbg.generated  Tue Apr 24 18:10:17 CST 2018
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ad_media_type.update_time
	 * @param updateTime  the value for ad_media_type.update_time
	 * @mbg.generated  Tue Apr 24 18:10:17 CST 2018
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}