package com.bt.om.entity;

import java.util.Date;

public class AdMonitorTaskFeedbackResources {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_monitor_task_feedback_resources.id
     *
     * @mbg.generated Wed Aug 08 10:35:35 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_monitor_task_feedback_resources.monitor_task_feedback_id
     *
     * @mbg.generated Wed Aug 08 10:35:35 CST 2018
     */
    private Integer monitorTaskFeedbackId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_monitor_task_feedback_resources.pic_url
     *
     * @mbg.generated Wed Aug 08 10:35:35 CST 2018
     */
    private String picUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_monitor_task_feedback_resources.pic_order
     *
     * @mbg.generated Wed Aug 08 10:35:35 CST 2018
     */
    private Integer picOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_monitor_task_feedback_resources.pic_status
     *
     * @mbg.generated Wed Aug 08 10:35:35 CST 2018
     */
    private Integer picStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_monitor_task_feedback_resources.create_time
     *
     * @mbg.generated Wed Aug 08 10:35:35 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_monitor_task_feedback_resources.update_time
     *
     * @mbg.generated Wed Aug 08 10:35:35 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_monitor_task_feedback_resources.id
     *
     * @return the value of ad_monitor_task_feedback_resources.id
     *
     * @mbg.generated Wed Aug 08 10:35:35 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_monitor_task_feedback_resources.id
     *
     * @param id the value for ad_monitor_task_feedback_resources.id
     *
     * @mbg.generated Wed Aug 08 10:35:35 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_monitor_task_feedback_resources.monitor_task_feedback_id
     *
     * @return the value of ad_monitor_task_feedback_resources.monitor_task_feedback_id
     *
     * @mbg.generated Wed Aug 08 10:35:35 CST 2018
     */
    public Integer getMonitorTaskFeedbackId() {
        return monitorTaskFeedbackId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_monitor_task_feedback_resources.monitor_task_feedback_id
     *
     * @param monitorTaskFeedbackId the value for ad_monitor_task_feedback_resources.monitor_task_feedback_id
     *
     * @mbg.generated Wed Aug 08 10:35:35 CST 2018
     */
    public void setMonitorTaskFeedbackId(Integer monitorTaskFeedbackId) {
        this.monitorTaskFeedbackId = monitorTaskFeedbackId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_monitor_task_feedback_resources.pic_url
     *
     * @return the value of ad_monitor_task_feedback_resources.pic_url
     *
     * @mbg.generated Wed Aug 08 10:35:35 CST 2018
     */
    public String getPicUrl() {
        return picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_monitor_task_feedback_resources.pic_url
     *
     * @param picUrl the value for ad_monitor_task_feedback_resources.pic_url
     *
     * @mbg.generated Wed Aug 08 10:35:35 CST 2018
     */
    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl == null ? null : picUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_monitor_task_feedback_resources.pic_order
     *
     * @return the value of ad_monitor_task_feedback_resources.pic_order
     *
     * @mbg.generated Wed Aug 08 10:35:35 CST 2018
     */
    public Integer getPicOrder() {
        return picOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_monitor_task_feedback_resources.pic_order
     *
     * @param picOrder the value for ad_monitor_task_feedback_resources.pic_order
     *
     * @mbg.generated Wed Aug 08 10:35:35 CST 2018
     */
    public void setPicOrder(Integer picOrder) {
        this.picOrder = picOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_monitor_task_feedback_resources.pic_status
     *
     * @return the value of ad_monitor_task_feedback_resources.pic_status
     *
     * @mbg.generated Wed Aug 08 10:35:35 CST 2018
     */
    public Integer getPicStatus() {
        return picStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_monitor_task_feedback_resources.pic_status
     *
     * @param picStatus the value for ad_monitor_task_feedback_resources.pic_status
     *
     * @mbg.generated Wed Aug 08 10:35:35 CST 2018
     */
    public void setPicStatus(Integer picStatus) {
        this.picStatus = picStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_monitor_task_feedback_resources.create_time
     *
     * @return the value of ad_monitor_task_feedback_resources.create_time
     *
     * @mbg.generated Wed Aug 08 10:35:35 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_monitor_task_feedback_resources.create_time
     *
     * @param createTime the value for ad_monitor_task_feedback_resources.create_time
     *
     * @mbg.generated Wed Aug 08 10:35:35 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_monitor_task_feedback_resources.update_time
     *
     * @return the value of ad_monitor_task_feedback_resources.update_time
     *
     * @mbg.generated Wed Aug 08 10:35:35 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_monitor_task_feedback_resources.update_time
     *
     * @param updateTime the value for ad_monitor_task_feedback_resources.update_time
     *
     * @mbg.generated Wed Aug 08 10:35:35 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}