package com.bt.om.entity;

import java.util.Date;

public class AdMonitorTask extends ID{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_monitor_task.id
     *
     * @mbggenerated Sat Jan 20 10:48:02 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_monitor_task.activity_id
     *
     * @mbggenerated Sat Jan 20 10:48:02 CST 2018
     */
    private Integer activityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_monitor_task.activity_adseat_id
     *
     * @mbggenerated Sat Jan 20 10:48:02 CST 2018
     */
    private Integer activityAdseatId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_monitor_task.task_type
     *
     * @mbggenerated Sat Jan 20 10:48:02 CST 2018
     */
    private Integer taskType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_monitor_task.user_id
     *
     * @mbggenerated Sat Jan 20 10:48:02 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_monitor_task.status
     *
     * @mbggenerated Sat Jan 20 10:48:02 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_monitor_task.create_time
     *
     * @mbggenerated Sat Jan 20 10:48:02 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_monitor_task.update_time
     *
     * @mbggenerated Sat Jan 20 10:48:02 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_monitor_task.id
     *
     * @return the value of ad_monitor_task.id
     *
     * @mbggenerated Sat Jan 20 10:48:02 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_monitor_task.id
     *
     * @param id the value for ad_monitor_task.id
     *
     * @mbggenerated Sat Jan 20 10:48:02 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_monitor_task.activity_id
     *
     * @return the value of ad_monitor_task.activity_id
     *
     * @mbggenerated Sat Jan 20 10:48:02 CST 2018
     */
    public Integer getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_monitor_task.activity_id
     *
     * @param activityId the value for ad_monitor_task.activity_id
     *
     * @mbggenerated Sat Jan 20 10:48:02 CST 2018
     */
    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_monitor_task.activity_adseat_id
     *
     * @return the value of ad_monitor_task.activity_adseat_id
     *
     * @mbggenerated Sat Jan 20 10:48:02 CST 2018
     */
    public Integer getActivityAdseatId() {
        return activityAdseatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_monitor_task.activity_adseat_id
     *
     * @param activityAdseatId the value for ad_monitor_task.activity_adseat_id
     *
     * @mbggenerated Sat Jan 20 10:48:02 CST 2018
     */
    public void setActivityAdseatId(Integer activityAdseatId) {
        this.activityAdseatId = activityAdseatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_monitor_task.task_type
     *
     * @return the value of ad_monitor_task.task_type
     *
     * @mbggenerated Sat Jan 20 10:48:02 CST 2018
     */
    public Integer getTaskType() {
        return taskType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_monitor_task.task_type
     *
     * @param taskType the value for ad_monitor_task.task_type
     *
     * @mbggenerated Sat Jan 20 10:48:02 CST 2018
     */
    public void setTaskType(Integer taskType) {
        this.taskType = taskType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_monitor_task.user_id
     *
     * @return the value of ad_monitor_task.user_id
     *
     * @mbggenerated Sat Jan 20 10:48:02 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_monitor_task.user_id
     *
     * @param userId the value for ad_monitor_task.user_id
     *
     * @mbggenerated Sat Jan 20 10:48:02 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_monitor_task.status
     *
     * @return the value of ad_monitor_task.status
     *
     * @mbggenerated Sat Jan 20 10:48:02 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_monitor_task.status
     *
     * @param status the value for ad_monitor_task.status
     *
     * @mbggenerated Sat Jan 20 10:48:02 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_monitor_task.create_time
     *
     * @return the value of ad_monitor_task.create_time
     *
     * @mbggenerated Sat Jan 20 10:48:02 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_monitor_task.create_time
     *
     * @param createTime the value for ad_monitor_task.create_time
     *
     * @mbggenerated Sat Jan 20 10:48:02 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_monitor_task.update_time
     *
     * @return the value of ad_monitor_task.update_time
     *
     * @mbggenerated Sat Jan 20 10:48:02 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_monitor_task.update_time
     *
     * @param updateTime the value for ad_monitor_task.update_time
     *
     * @mbggenerated Sat Jan 20 10:48:02 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}