package com.bt.om.entity;

import java.util.Date;

public class AdMonitorReward extends ID {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_monitor_reward.id
     *
     * @mbggenerated Fri Jan 26 14:10:24 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_monitor_reward.monitor_task_id
     *
     * @mbggenerated Fri Jan 26 14:10:24 CST 2018
     */
    private Integer monitorTaskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_monitor_reward.user_id
     *
     * @mbggenerated Fri Jan 26 14:10:24 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_monitor_reward.type
     *
     * @mbggenerated Fri Jan 26 14:10:24 CST 2018
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_monitor_reward.task_type
     *
     * @mbggenerated Fri Jan 26 14:10:24 CST 2018
     */
    private Integer taskType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_monitor_reward.reward_points
     *
     * @mbggenerated Fri Jan 26 14:10:24 CST 2018
     */
    private Integer rewardPoints;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_monitor_reward.create_time
     *
     * @mbggenerated Fri Jan 26 14:10:24 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_monitor_reward.update_time
     *
     * @mbggenerated Fri Jan 26 14:10:24 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_monitor_reward.id
     *
     * @return the value of ad_monitor_reward.id
     *
     * @mbggenerated Fri Jan 26 14:10:24 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_monitor_reward.id
     *
     * @param id the value for ad_monitor_reward.id
     *
     * @mbggenerated Fri Jan 26 14:10:24 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_monitor_reward.monitor_task_id
     *
     * @return the value of ad_monitor_reward.monitor_task_id
     *
     * @mbggenerated Fri Jan 26 14:10:24 CST 2018
     */
    public Integer getMonitorTaskId() {
        return monitorTaskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_monitor_reward.monitor_task_id
     *
     * @param monitorTaskId the value for ad_monitor_reward.monitor_task_id
     *
     * @mbggenerated Fri Jan 26 14:10:24 CST 2018
     */
    public void setMonitorTaskId(Integer monitorTaskId) {
        this.monitorTaskId = monitorTaskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_monitor_reward.user_id
     *
     * @return the value of ad_monitor_reward.user_id
     *
     * @mbggenerated Fri Jan 26 14:10:24 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_monitor_reward.user_id
     *
     * @param userId the value for ad_monitor_reward.user_id
     *
     * @mbggenerated Fri Jan 26 14:10:24 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_monitor_reward.type
     *
     * @return the value of ad_monitor_reward.type
     *
     * @mbggenerated Fri Jan 26 14:10:24 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_monitor_reward.type
     *
     * @param type the value for ad_monitor_reward.type
     *
     * @mbggenerated Fri Jan 26 14:10:24 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_monitor_reward.task_type
     *
     * @return the value of ad_monitor_reward.task_type
     *
     * @mbggenerated Fri Jan 26 14:10:24 CST 2018
     */
    public Integer getTaskType() {
        return taskType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_monitor_reward.task_type
     *
     * @param taskType the value for ad_monitor_reward.task_type
     *
     * @mbggenerated Fri Jan 26 14:10:24 CST 2018
     */
    public void setTaskType(Integer taskType) {
        this.taskType = taskType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_monitor_reward.reward_points
     *
     * @return the value of ad_monitor_reward.reward_points
     *
     * @mbggenerated Fri Jan 26 14:10:24 CST 2018
     */
    public Integer getRewardPoints() {
        return rewardPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_monitor_reward.reward_points
     *
     * @param rewardPoints the value for ad_monitor_reward.reward_points
     *
     * @mbggenerated Fri Jan 26 14:10:24 CST 2018
     */
    public void setRewardPoints(Integer rewardPoints) {
        this.rewardPoints = rewardPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_monitor_reward.create_time
     *
     * @return the value of ad_monitor_reward.create_time
     *
     * @mbggenerated Fri Jan 26 14:10:24 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_monitor_reward.create_time
     *
     * @param createTime the value for ad_monitor_reward.create_time
     *
     * @mbggenerated Fri Jan 26 14:10:24 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_monitor_reward.update_time
     *
     * @return the value of ad_monitor_reward.update_time
     *
     * @mbggenerated Fri Jan 26 14:10:24 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_monitor_reward.update_time
     *
     * @param updateTime the value for ad_monitor_reward.update_time
     *
     * @mbggenerated Fri Jan 26 14:10:24 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}