package com.bt.om.entity;

import java.util.Date;

public class AdPoint {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ad_point.id
	 * @mbg.generated  Thu May 31 11:11:28 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ad_point.type
	 * @mbg.generated  Thu May 31 11:11:28 CST 2018
	 */
	private int type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ad_point.name
	 * @mbg.generated  Thu May 31 11:11:28 CST 2018
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ad_point.point
	 * @mbg.generated  Thu May 31 11:11:28 CST 2018
	 */
	private Integer point;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ad_point.create_time
	 * @mbg.generated  Thu May 31 11:11:28 CST 2018
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ad_point.update_time
	 * @mbg.generated  Thu May 31 11:11:28 CST 2018
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ad_point.id
	 * @return  the value of ad_point.id
	 * @mbg.generated  Thu May 31 11:11:28 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ad_point.id
	 * @param id  the value for ad_point.id
	 * @mbg.generated  Thu May 31 11:11:28 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ad_point.type
	 * @return  the value of ad_point.type
	 * @mbg.generated  Thu May 31 11:11:28 CST 2018
	 */
	public int getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ad_point.type
	 * @param type  the value for ad_point.type
	 * @mbg.generated  Thu May 31 11:11:28 CST 2018
	 */
	public void setType(int type) {
		this.type = type;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ad_point.name
	 * @return  the value of ad_point.point
	 * @mbg.generated  Thu May 31 11:11:28 CST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ad_point.name
	 * @param point  the value for ad_point.point
	 * @mbg.generated  Thu May 31 11:11:28 CST 2018
	 */
	public void setName(String name) {
		this.name = name;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ad_point.point
	 * @return  the value of ad_point.point
	 * @mbg.generated  Thu May 31 11:11:28 CST 2018
	 */
	public Integer getPoint() {
		return point;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ad_point.point
	 * @param point  the value for ad_point.point
	 * @mbg.generated  Thu May 31 11:11:28 CST 2018
	 */
	public void setPoint(Integer point) {
		this.point = point;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ad_point.create_time
	 * @return  the value of ad_point.create_time
	 * @mbg.generated  Thu May 31 11:11:28 CST 2018
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ad_point.create_time
	 * @param createTime  the value for ad_point.create_time
	 * @mbg.generated  Thu May 31 11:11:28 CST 2018
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ad_point.update_time
	 * @return  the value of ad_point.update_time
	 * @mbg.generated  Thu May 31 11:11:28 CST 2018
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ad_point.update_time
	 * @param updateTime  the value for ad_point.update_time
	 * @mbg.generated  Thu May 31 11:11:28 CST 2018
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}


}
