package com.bt.om.entity;

import java.util.Date;

public class AdSeatInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_seat_info.id
     *
     * @mbggenerated Thu Feb 01 13:48:16 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_seat_info.name
     *
     * @mbggenerated Thu Feb 01 13:48:16 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_seat_info.province
     *
     * @mbggenerated Thu Feb 01 13:48:16 CST 2018
     */
    private Integer province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_seat_info.city
     *
     * @mbggenerated Thu Feb 01 13:48:16 CST 2018
     */
    private Integer city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_seat_info.region
     *
     * @mbggenerated Thu Feb 01 13:48:16 CST 2018
     */
    private Integer region;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_seat_info.street
     *
     * @mbggenerated Thu Feb 01 13:48:16 CST 2018
     */
    private Integer street;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_seat_info.media_id
     *
     * @mbggenerated Thu Feb 01 13:48:16 CST 2018
     */
    private Integer mediaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_seat_info.ad_seat_type
     *
     * @mbggenerated Thu Feb 01 13:48:16 CST 2018
     */
    private Integer adSeatType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_seat_info.ad_code
     *
     * @mbggenerated Thu Feb 01 13:48:16 CST 2018
     */
    private String adCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_seat_info.location
     *
     * @mbggenerated Thu Feb 01 13:48:16 CST 2018
     */
    private String location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_seat_info.ad_size
     *
     * @mbggenerated Thu Feb 01 13:48:16 CST 2018
     */
    private String adSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_seat_info.pv
     *
     * @mbggenerated Thu Feb 01 13:48:16 CST 2018
     */
    private Integer pv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_seat_info.private_car_pv
     *
     * @mbggenerated Thu Feb 01 13:48:16 CST 2018
     */
    private Integer privateCarPv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_seat_info.bus_pv
     *
     * @mbggenerated Thu Feb 01 13:48:16 CST 2018
     */
    private Integer busPv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_seat_info.lon
     *
     * @mbggenerated Thu Feb 01 13:48:16 CST 2018
     */
    private Double lon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_seat_info.lat
     *
     * @mbggenerated Thu Feb 01 13:48:16 CST 2018
     */
    private Double lat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_seat_info.create_time
     *
     * @mbggenerated Thu Feb 01 13:48:16 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_seat_info.update_time
     *
     * @mbggenerated Thu Feb 01 13:48:16 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_seat_info.id
     *
     * @return the value of ad_seat_info.id
     *
     * @mbggenerated Thu Feb 01 13:48:16 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_seat_info.id
     *
     * @param id the value for ad_seat_info.id
     *
     * @mbggenerated Thu Feb 01 13:48:16 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_seat_info.name
     *
     * @return the value of ad_seat_info.name
     *
     * @mbggenerated Thu Feb 01 13:48:16 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_seat_info.name
     *
     * @param name the value for ad_seat_info.name
     *
     * @mbggenerated Thu Feb 01 13:48:16 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_seat_info.province
     *
     * @return the value of ad_seat_info.province
     *
     * @mbggenerated Thu Feb 01 13:48:16 CST 2018
     */
    public Integer getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_seat_info.province
     *
     * @param province the value for ad_seat_info.province
     *
     * @mbggenerated Thu Feb 01 13:48:16 CST 2018
     */
    public void setProvince(Integer province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_seat_info.city
     *
     * @return the value of ad_seat_info.city
     *
     * @mbggenerated Thu Feb 01 13:48:16 CST 2018
     */
    public Integer getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_seat_info.city
     *
     * @param city the value for ad_seat_info.city
     *
     * @mbggenerated Thu Feb 01 13:48:16 CST 2018
     */
    public void setCity(Integer city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_seat_info.region
     *
     * @return the value of ad_seat_info.region
     *
     * @mbggenerated Thu Feb 01 13:48:16 CST 2018
     */
    public Integer getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_seat_info.region
     *
     * @param region the value for ad_seat_info.region
     *
     * @mbggenerated Thu Feb 01 13:48:16 CST 2018
     */
    public void setRegion(Integer region) {
        this.region = region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_seat_info.street
     *
     * @return the value of ad_seat_info.street
     *
     * @mbggenerated Thu Feb 01 13:48:16 CST 2018
     */
    public Integer getStreet() {
        return street;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_seat_info.street
     *
     * @param street the value for ad_seat_info.street
     *
     * @mbggenerated Thu Feb 01 13:48:16 CST 2018
     */
    public void setStreet(Integer street) {
        this.street = street;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_seat_info.media_id
     *
     * @return the value of ad_seat_info.media_id
     *
     * @mbggenerated Thu Feb 01 13:48:16 CST 2018
     */
    public Integer getMediaId() {
        return mediaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_seat_info.media_id
     *
     * @param mediaId the value for ad_seat_info.media_id
     *
     * @mbggenerated Thu Feb 01 13:48:16 CST 2018
     */
    public void setMediaId(Integer mediaId) {
        this.mediaId = mediaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_seat_info.ad_seat_type
     *
     * @return the value of ad_seat_info.ad_seat_type
     *
     * @mbggenerated Thu Feb 01 13:48:16 CST 2018
     */
    public Integer getAdSeatType() {
        return adSeatType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_seat_info.ad_seat_type
     *
     * @param adSeatType the value for ad_seat_info.ad_seat_type
     *
     * @mbggenerated Thu Feb 01 13:48:16 CST 2018
     */
    public void setAdSeatType(Integer adSeatType) {
        this.adSeatType = adSeatType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_seat_info.ad_code
     *
     * @return the value of ad_seat_info.ad_code
     *
     * @mbggenerated Thu Feb 01 13:48:16 CST 2018
     */
    public String getAdCode() {
        return adCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_seat_info.ad_code
     *
     * @param adCode the value for ad_seat_info.ad_code
     *
     * @mbggenerated Thu Feb 01 13:48:16 CST 2018
     */
    public void setAdCode(String adCode) {
        this.adCode = adCode == null ? null : adCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_seat_info.location
     *
     * @return the value of ad_seat_info.location
     *
     * @mbggenerated Thu Feb 01 13:48:16 CST 2018
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_seat_info.location
     *
     * @param location the value for ad_seat_info.location
     *
     * @mbggenerated Thu Feb 01 13:48:16 CST 2018
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_seat_info.ad_size
     *
     * @return the value of ad_seat_info.ad_size
     *
     * @mbggenerated Thu Feb 01 13:48:16 CST 2018
     */
    public String getAdSize() {
        return adSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_seat_info.ad_size
     *
     * @param adSize the value for ad_seat_info.ad_size
     *
     * @mbggenerated Thu Feb 01 13:48:16 CST 2018
     */
    public void setAdSize(String adSize) {
        this.adSize = adSize == null ? null : adSize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_seat_info.pv
     *
     * @return the value of ad_seat_info.pv
     *
     * @mbggenerated Thu Feb 01 13:48:16 CST 2018
     */
    public Integer getPv() {
        return pv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_seat_info.pv
     *
     * @param pv the value for ad_seat_info.pv
     *
     * @mbggenerated Thu Feb 01 13:48:16 CST 2018
     */
    public void setPv(Integer pv) {
        this.pv = pv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_seat_info.private_car_pv
     *
     * @return the value of ad_seat_info.private_car_pv
     *
     * @mbggenerated Thu Feb 01 13:48:16 CST 2018
     */
    public Integer getPrivateCarPv() {
        return privateCarPv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_seat_info.private_car_pv
     *
     * @param privateCarPv the value for ad_seat_info.private_car_pv
     *
     * @mbggenerated Thu Feb 01 13:48:16 CST 2018
     */
    public void setPrivateCarPv(Integer privateCarPv) {
        this.privateCarPv = privateCarPv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_seat_info.bus_pv
     *
     * @return the value of ad_seat_info.bus_pv
     *
     * @mbggenerated Thu Feb 01 13:48:16 CST 2018
     */
    public Integer getBusPv() {
        return busPv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_seat_info.bus_pv
     *
     * @param busPv the value for ad_seat_info.bus_pv
     *
     * @mbggenerated Thu Feb 01 13:48:16 CST 2018
     */
    public void setBusPv(Integer busPv) {
        this.busPv = busPv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_seat_info.lon
     *
     * @return the value of ad_seat_info.lon
     *
     * @mbggenerated Thu Feb 01 13:48:16 CST 2018
     */
    public Double getLon() {
        return lon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_seat_info.lon
     *
     * @param lon the value for ad_seat_info.lon
     *
     * @mbggenerated Thu Feb 01 13:48:16 CST 2018
     */
    public void setLon(Double lon) {
        this.lon = lon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_seat_info.lat
     *
     * @return the value of ad_seat_info.lat
     *
     * @mbggenerated Thu Feb 01 13:48:16 CST 2018
     */
    public Double getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_seat_info.lat
     *
     * @param lat the value for ad_seat_info.lat
     *
     * @mbggenerated Thu Feb 01 13:48:16 CST 2018
     */
    public void setLat(Double lat) {
        this.lat = lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_seat_info.create_time
     *
     * @return the value of ad_seat_info.create_time
     *
     * @mbggenerated Thu Feb 01 13:48:16 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_seat_info.create_time
     *
     * @param createTime the value for ad_seat_info.create_time
     *
     * @mbggenerated Thu Feb 01 13:48:16 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_seat_info.update_time
     *
     * @return the value of ad_seat_info.update_time
     *
     * @mbggenerated Thu Feb 01 13:48:16 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_seat_info.update_time
     *
     * @param updateTime the value for ad_seat_info.update_time
     *
     * @mbggenerated Thu Feb 01 13:48:16 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}