package com.bt.om.entity;

import java.util.Date;

public class AdUserMessage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_message.id
     *
     * @mbg.generated Tue Jun 19 15:09:44 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_message.target_id
     *
     * @mbg.generated Tue Jun 19 15:09:44 CST 2018
     */
    private Integer targetId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_message.target_user_id
     *
     * @mbg.generated Tue Jun 19 15:09:44 CST 2018
     */
    private Integer targetUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_message.type
     *
     * @mbg.generated Tue Jun 19 15:09:44 CST 2018
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_message.content
     *
     * @mbg.generated Tue Jun 19 15:09:44 CST 2018
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_message.is_finish
     *
     * @mbg.generated Tue Jun 19 15:09:44 CST 2018
     */
    private Integer isFinish;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_message.create_time
     *
     * @mbg.generated Tue Jun 19 15:09:44 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_message.update_time
     *
     * @mbg.generated Tue Jun 19 15:09:44 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_message.id
     *
     * @return the value of sys_user_message.id
     *
     * @mbg.generated Tue Jun 19 15:09:44 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_message.id
     *
     * @param id the value for sys_user_message.id
     *
     * @mbg.generated Tue Jun 19 15:09:44 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_message.target_id
     *
     * @return the value of sys_user_message.target_id
     *
     * @mbg.generated Tue Jun 19 15:09:44 CST 2018
     */
    public Integer getTargetId() {
        return targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_message.target_id
     *
     * @param targetId the value for sys_user_message.target_id
     *
     * @mbg.generated Tue Jun 19 15:09:44 CST 2018
     */
    public void setTargetId(Integer targetId) {
        this.targetId = targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_message.target_user_id
     *
     * @return the value of sys_user_message.target_user_id
     *
     * @mbg.generated Tue Jun 19 15:09:44 CST 2018
     */
    public Integer getTargetUserId() {
        return targetUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_message.target_user_id
     *
     * @param targetUserId the value for sys_user_message.target_user_id
     *
     * @mbg.generated Tue Jun 19 15:09:44 CST 2018
     */
    public void setTargetUserId(Integer targetUserId) {
        this.targetUserId = targetUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_message.type
     *
     * @return the value of sys_user_message.type
     *
     * @mbg.generated Tue Jun 19 15:09:44 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_message.type
     *
     * @param type the value for sys_user_message.type
     *
     * @mbg.generated Tue Jun 19 15:09:44 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_message.content
     *
     * @return the value of sys_user_message.content
     *
     * @mbg.generated Tue Jun 19 15:09:44 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_message.content
     *
     * @param content the value for sys_user_message.content
     *
     * @mbg.generated Tue Jun 19 15:09:44 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_message.is_finish
     *
     * @return the value of sys_user_message.is_finish
     *
     * @mbg.generated Tue Jun 19 15:09:44 CST 2018
     */
    public Integer getIsFinish() {
        return isFinish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_message.is_finish
     *
     * @param isFinish the value for sys_user_message.is_finish
     *
     * @mbg.generated Tue Jun 19 15:09:44 CST 2018
     */
    public void setIsFinish(Integer isFinish) {
        this.isFinish = isFinish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_message.create_time
     *
     * @return the value of sys_user_message.create_time
     *
     * @mbg.generated Tue Jun 19 15:09:44 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_message.create_time
     *
     * @param createTime the value for sys_user_message.create_time
     *
     * @mbg.generated Tue Jun 19 15:09:44 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_message.update_time
     *
     * @return the value of sys_user_message.update_time
     *
     * @mbg.generated Tue Jun 19 15:09:44 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_message.update_time
     *
     * @param updateTime the value for sys_user_message.update_time
     *
     * @mbg.generated Tue Jun 19 15:09:44 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}