package com.bt.om.entity;

public class City {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column citys.id
     *
     * @mbggenerated Sun Feb 11 17:57:54 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column citys.name
     *
     * @mbggenerated Sun Feb 11 17:57:54 CST 2018
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column citys.id
     *
     * @return the value of citys.id
     *
     * @mbggenerated Sun Feb 11 17:57:54 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column citys.id
     *
     * @param id the value for citys.id
     *
     * @mbggenerated Sun Feb 11 17:57:54 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column citys.name
     *
     * @return the value of citys.name
     *
     * @mbggenerated Sun Feb 11 17:57:54 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column citys.name
     *
     * @param name the value for citys.name
     *
     * @mbggenerated Sun Feb 11 17:57:54 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}