package com.bt.om.entity;

import java.util.Date;

public class DrawCash extends ID{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column draw_cash.id
     *
     * @mbg.generated Wed Feb 07 19:58:30 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column draw_cash.user_id
     *
     * @mbg.generated Wed Feb 07 19:58:30 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column draw_cash.cash
     *
     * @mbg.generated Wed Feb 07 19:58:30 CST 2018
     */
    private Double cash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column draw_cash.status
     *
     * @mbg.generated Wed Feb 07 19:58:30 CST 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column draw_cash.create_time
     *
     * @mbg.generated Wed Feb 07 19:58:30 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column draw_cash.update_time
     *
     * @mbg.generated Wed Feb 07 19:58:30 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column draw_cash.id
     *
     * @return the value of draw_cash.id
     *
     * @mbg.generated Wed Feb 07 19:58:30 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column draw_cash.id
     *
     * @param id the value for draw_cash.id
     *
     * @mbg.generated Wed Feb 07 19:58:30 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column draw_cash.user_id
     *
     * @return the value of draw_cash.user_id
     *
     * @mbg.generated Wed Feb 07 19:58:30 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column draw_cash.user_id
     *
     * @param userId the value for draw_cash.user_id
     *
     * @mbg.generated Wed Feb 07 19:58:30 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column draw_cash.cash
     *
     * @return the value of draw_cash.cash
     *
     * @mbg.generated Wed Feb 07 19:58:30 CST 2018
     */
    public Double getCash() {
        return cash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column draw_cash.cash
     *
     * @param cash the value for draw_cash.cash
     *
     * @mbg.generated Wed Feb 07 19:58:30 CST 2018
     */
    public void setCash(Double cash) {
        this.cash = cash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column draw_cash.status
     *
     * @return the value of draw_cash.status
     *
     * @mbg.generated Wed Feb 07 19:58:30 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column draw_cash.status
     *
     * @param status the value for draw_cash.status
     *
     * @mbg.generated Wed Feb 07 19:58:30 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column draw_cash.create_time
     *
     * @return the value of draw_cash.create_time
     *
     * @mbg.generated Wed Feb 07 19:58:30 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column draw_cash.create_time
     *
     * @param createTime the value for draw_cash.create_time
     *
     * @mbg.generated Wed Feb 07 19:58:30 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column draw_cash.update_time
     *
     * @return the value of draw_cash.update_time
     *
     * @mbg.generated Wed Feb 07 19:58:30 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column draw_cash.update_time
     *
     * @param updateTime the value for draw_cash.update_time
     *
     * @mbg.generated Wed Feb 07 19:58:30 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}