package com.bt.om.entity;

import java.util.Date;

import jxl.write.DateTime;

public class LoginLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_log.id
     *
     * @mbg.generated Mon Jul 16 11:07:08 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_log.user_id
     *
     * @mbg.generated Mon Jul 16 11:07:08 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_log.type
     *
     * @mbg.generated Mon Jul 16 11:07:08 CST 2018
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_log.ip
     *
     * @mbg.generated Mon Jul 16 11:07:08 CST 2018
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_log.location
     *
     * @mbg.generated Mon Jul 16 11:07:08 CST 2018
     */
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_log.create_time
     *
     * @mbg.generated Mon Jul 16 11:07:08 CST 2018
     */
    private Date createTime;

  

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_log.id
     *
     * @return the value of login_log.id
     *
     * @mbg.generated Mon Jul 16 11:07:08 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_log.id
     *
     * @param id the value for login_log.id
     *
     * @mbg.generated Mon Jul 16 11:07:08 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_log.user_id
     *
     * @return the value of login_log.user_id
     *
     * @mbg.generated Mon Jul 16 11:07:08 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_log.user_id
     *
     * @param userId the value for login_log.user_id
     *
     * @mbg.generated Mon Jul 16 11:07:08 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_log.type
     *
     * @return the value of login_log.type
     *
     * @mbg.generated Mon Jul 16 11:07:08 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_log.type
     *
     * @param type the value for login_log.type
     *
     * @mbg.generated Mon Jul 16 11:07:08 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_log.ip
     *
     * @return the value of login_log.ip
     *
     * @mbg.generated Mon Jul 16 11:07:08 CST 2018
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_log.ip
     *
     * @param ip the value for login_log.ip
     *
     * @mbg.generated Mon Jul 16 11:07:08 CST 2018
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_log.location
     *
     * @return the value of login_log.location
     *
     * @mbg.generated Mon Jul 16 11:07:08 CST 2018
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_log.location
     *
     * @param location the value for login_log.location
     *
     * @mbg.generated Mon Jul 16 11:07:08 CST 2018
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_log.create_time
     *
     * @return the value of login_log.create_time
     *
     * @mbg.generated Mon Jul 16 11:07:08 CST 2018
     */

}