package com.bt.om.entity;

import java.util.Date;

public class OperateLog {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column operate_log.id
	 * @mbg.generated  Thu May 24 14:15:30 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column operate_log.user_id
	 * @mbg.generated  Thu May 24 14:15:30 CST 2018
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column operate_log.content
	 * @mbg.generated  Thu May 24 14:15:30 CST 2018
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column operate_log.create_time
	 * @mbg.generated  Thu May 24 14:15:30 CST 2018
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column operate_log.update_time
	 * @mbg.generated  Thu May 24 14:15:30 CST 2018
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column operate_log.id
	 * @return  the value of operate_log.id
	 * @mbg.generated  Thu May 24 14:15:30 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column operate_log.id
	 * @param id  the value for operate_log.id
	 * @mbg.generated  Thu May 24 14:15:30 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column operate_log.user_id
	 * @return  the value of operate_log.user_id
	 * @mbg.generated  Thu May 24 14:15:30 CST 2018
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column operate_log.user_id
	 * @param userId  the value for operate_log.user_id
	 * @mbg.generated  Thu May 24 14:15:30 CST 2018
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column operate_log.content
	 * @return  the value of operate_log.content
	 * @mbg.generated  Thu May 24 14:15:30 CST 2018
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column operate_log.content
	 * @param content  the value for operate_log.content
	 * @mbg.generated  Thu May 24 14:15:30 CST 2018
	 */
	public void setContent(String content) {
		this.content = content == null ? null : content.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column operate_log.create_time
	 * @return  the value of operate_log.create_time
	 * @mbg.generated  Thu May 24 14:15:30 CST 2018
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column operate_log.create_time
	 * @param createTime  the value for operate_log.create_time
	 * @mbg.generated  Thu May 24 14:15:30 CST 2018
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column operate_log.update_time
	 * @return  the value of operate_log.update_time
	 * @mbg.generated  Thu May 24 14:15:30 CST 2018
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column operate_log.update_time
	 * @param updateTime  the value for operate_log.update_time
	 * @mbg.generated  Thu May 24 14:15:30 CST 2018
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}