package com.bt.om.entity;

import java.util.Date;

public class ProductInfo extends ID{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.id
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_id
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    private String productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_name
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_img_url
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    private String productImgUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_info_url
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    private String productInfoUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_cat
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    private String productCat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.tk_link
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    private String tkLink;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.price
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.month_sales
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    private Integer monthSales;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.income_rate
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    private Float incomeRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.commission
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    private Float commission;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.seller_wangwang
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    private String sellerWangwang;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.seller_id
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    private String sellerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.shop_name
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    private String shopName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.platform_type
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    private String platformType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.coupon_id
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    private String couponId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.coupon_total
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    private Integer couponTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.coupon_rest
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    private Integer couponRest;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.coupon_miane
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    private String couponMiane;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.coupon_start
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    private String couponStart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.coupon_end
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    private String couponEnd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.coupon_link
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    private String couponLink;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.coupon_promo_link
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    private String couponPromoLink;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.create_time
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.update_time
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    private Date updateTime;
    
    private int size;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.id
     *
     * @return the value of product_info.id
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.id
     *
     * @param id the value for product_info.id
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.product_id
     *
     * @return the value of product_info.product_id
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.product_id
     *
     * @param productId the value for product_info.product_id
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.product_name
     *
     * @return the value of product_info.product_name
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.product_name
     *
     * @param productName the value for product_info.product_name
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.product_img_url
     *
     * @return the value of product_info.product_img_url
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public String getProductImgUrl() {
        return productImgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.product_img_url
     *
     * @param productImgUrl the value for product_info.product_img_url
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public void setProductImgUrl(String productImgUrl) {
        this.productImgUrl = productImgUrl == null ? null : productImgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.product_info_url
     *
     * @return the value of product_info.product_info_url
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public String getProductInfoUrl() {
        return productInfoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.product_info_url
     *
     * @param productInfoUrl the value for product_info.product_info_url
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public void setProductInfoUrl(String productInfoUrl) {
        this.productInfoUrl = productInfoUrl == null ? null : productInfoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.product_cat
     *
     * @return the value of product_info.product_cat
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public String getProductCat() {
        return productCat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.product_cat
     *
     * @param productCat the value for product_info.product_cat
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public void setProductCat(String productCat) {
        this.productCat = productCat == null ? null : productCat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.tk_link
     *
     * @return the value of product_info.tk_link
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public String getTkLink() {
        return tkLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.tk_link
     *
     * @param tkLink the value for product_info.tk_link
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public void setTkLink(String tkLink) {
        this.tkLink = tkLink == null ? null : tkLink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.price
     *
     * @return the value of product_info.price
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.price
     *
     * @param price the value for product_info.price
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.month_sales
     *
     * @return the value of product_info.month_sales
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public Integer getMonthSales() {
        return monthSales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.month_sales
     *
     * @param monthSales the value for product_info.month_sales
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public void setMonthSales(Integer monthSales) {
        this.monthSales = monthSales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.income_rate
     *
     * @return the value of product_info.income_rate
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public Float getIncomeRate() {
        return incomeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.income_rate
     *
     * @param incomeRate the value for product_info.income_rate
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public void setIncomeRate(Float incomeRate) {
        this.incomeRate = incomeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.commission
     *
     * @return the value of product_info.commission
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public Float getCommission() {
        return commission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.commission
     *
     * @param commission the value for product_info.commission
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public void setCommission(Float commission) {
        this.commission = commission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.seller_wangwang
     *
     * @return the value of product_info.seller_wangwang
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public String getSellerWangwang() {
        return sellerWangwang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.seller_wangwang
     *
     * @param sellerWangwang the value for product_info.seller_wangwang
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public void setSellerWangwang(String sellerWangwang) {
        this.sellerWangwang = sellerWangwang == null ? null : sellerWangwang.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.seller_id
     *
     * @return the value of product_info.seller_id
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public String getSellerId() {
        return sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.seller_id
     *
     * @param sellerId the value for product_info.seller_id
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public void setSellerId(String sellerId) {
        this.sellerId = sellerId == null ? null : sellerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.shop_name
     *
     * @return the value of product_info.shop_name
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public String getShopName() {
        return shopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.shop_name
     *
     * @param shopName the value for product_info.shop_name
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public void setShopName(String shopName) {
        this.shopName = shopName == null ? null : shopName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.platform_type
     *
     * @return the value of product_info.platform_type
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public String getPlatformType() {
        return platformType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.platform_type
     *
     * @param platformType the value for product_info.platform_type
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public void setPlatformType(String platformType) {
        this.platformType = platformType == null ? null : platformType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.coupon_id
     *
     * @return the value of product_info.coupon_id
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public String getCouponId() {
        return couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.coupon_id
     *
     * @param couponId the value for product_info.coupon_id
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public void setCouponId(String couponId) {
        this.couponId = couponId == null ? null : couponId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.coupon_total
     *
     * @return the value of product_info.coupon_total
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public Integer getCouponTotal() {
        return couponTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.coupon_total
     *
     * @param couponTotal the value for product_info.coupon_total
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public void setCouponTotal(Integer couponTotal) {
        this.couponTotal = couponTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.coupon_rest
     *
     * @return the value of product_info.coupon_rest
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public Integer getCouponRest() {
        return couponRest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.coupon_rest
     *
     * @param couponRest the value for product_info.coupon_rest
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public void setCouponRest(Integer couponRest) {
        this.couponRest = couponRest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.coupon_miane
     *
     * @return the value of product_info.coupon_miane
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public String getCouponMiane() {
        return couponMiane;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.coupon_miane
     *
     * @param couponMiane the value for product_info.coupon_miane
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public void setCouponMiane(String couponMiane) {
        this.couponMiane = couponMiane == null ? null : couponMiane.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.coupon_start
     *
     * @return the value of product_info.coupon_start
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public String getCouponStart() {
        return couponStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.coupon_start
     *
     * @param couponStart the value for product_info.coupon_start
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public void setCouponStart(String couponStart) {
        this.couponStart = couponStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.coupon_end
     *
     * @return the value of product_info.coupon_end
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public String getCouponEnd() {
        return couponEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.coupon_end
     *
     * @param couponEnd the value for product_info.coupon_end
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public void setCouponEnd(String couponEnd) {
        this.couponEnd = couponEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.coupon_link
     *
     * @return the value of product_info.coupon_link
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public String getCouponLink() {
        return couponLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.coupon_link
     *
     * @param couponLink the value for product_info.coupon_link
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public void setCouponLink(String couponLink) {
        this.couponLink = couponLink == null ? null : couponLink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.coupon_promo_link
     *
     * @return the value of product_info.coupon_promo_link
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public String getCouponPromoLink() {
        return couponPromoLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.coupon_promo_link
     *
     * @param couponPromoLink the value for product_info.coupon_promo_link
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public void setCouponPromoLink(String couponPromoLink) {
        this.couponPromoLink = couponPromoLink == null ? null : couponPromoLink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.create_time
     *
     * @return the value of product_info.create_time
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.create_time
     *
     * @param createTime the value for product_info.create_time
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.update_time
     *
     * @return the value of product_info.update_time
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.update_time
     *
     * @param updateTime the value for product_info.update_time
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

	public int getSize() {
		return size;
	}

	public void setSize(int size) {
		this.size = size;
	}
    
    
}