package com.bt.om.entity;

import java.util.Date;

public class SysOrder extends ID{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_order.id
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_order.order_id
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_order.product_id
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    private String productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_order.commission
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    private Double commission;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_order.status
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_order.create_time
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_order.update_time
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_order.id
     *
     * @return the value of sys_order.id
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_order.id
     *
     * @param id the value for sys_order.id
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_order.order_id
     *
     * @return the value of sys_order.order_id
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_order.order_id
     *
     * @param orderId the value for sys_order.order_id
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_order.product_id
     *
     * @return the value of sys_order.product_id
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_order.product_id
     *
     * @param productId the value for sys_order.product_id
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_order.commission
     *
     * @return the value of sys_order.commission
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public Double getCommission() {
        return commission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_order.commission
     *
     * @param commission the value for sys_order.commission
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public void setCommission(Double commission) {
        this.commission = commission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_order.status
     *
     * @return the value of sys_order.status
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_order.status
     *
     * @param status the value for sys_order.status
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_order.create_time
     *
     * @return the value of sys_order.create_time
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_order.create_time
     *
     * @param createTime the value for sys_order.create_time
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_order.update_time
     *
     * @return the value of sys_order.update_time
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_order.update_time
     *
     * @param updateTime the value for sys_order.update_time
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}