package com.bt.om.entity;

import java.util.Date;

public class SysResources {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.id
     *
     * @mbg.generated Tue Apr 24 17:02:34 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.name
     *
     * @mbg.generated Tue Apr 24 17:02:34 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.parentId
     *
     * @mbg.generated Tue Apr 24 17:02:34 CST 2018
     */
    private Integer parentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.type
     *
     * @mbg.generated Tue Apr 24 17:02:34 CST 2018
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.user_id
     *
     * @mbg.generated Tue Apr 24 17:02:34 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.create_time
     *
     * @mbg.generated Tue Apr 24 17:02:34 CST 2018
     */
    private Date createTime;
    
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.update_time
     *
     * @mbg.generated Tue Apr 24 17:02:34 CST 2018
     */
    private Date updateTime;
    
    private Integer departmentType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.id
     *
     * @return the value of sys_resources.id
     *
     * @mbg.generated Tue Apr 24 17:02:34 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.id
     *
     * @param id the value for sys_resources.id
     *
     * @mbg.generated Tue Apr 24 17:02:34 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.name
     *
     * @return the value of sys_resources.name
     *
     * @mbg.generated Tue Apr 24 17:02:34 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.name
     *
     * @param name the value for sys_resources.name
     *
     * @mbg.generated Tue Apr 24 17:02:34 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.parentId
     *
     * @return the value of sys_resources.parentId
     *
     * @mbg.generated Tue Apr 24 17:02:34 CST 2018
     */
    public Integer getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.parentId
     *
     * @param parentid the value for sys_resources.parentId
     *
     * @mbg.generated Tue Apr 24 17:02:34 CST 2018
     */
    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.type
     *
     * @return the value of sys_resources.type
     *
     * @mbg.generated Tue Apr 24 17:02:34 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.type
     *
     * @param type the value for sys_resources.type
     *
     * @mbg.generated Tue Apr 24 17:02:34 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.user_id
     *
     * @return the value of sys_resources.user_id
     *
     * @mbg.generated Tue Apr 24 17:02:34 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.user_id
     *
     * @param userId the value for sys_resources.user_id
     *
     * @mbg.generated Tue Apr 24 17:02:34 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.create_time
     *
     * @return the value of sys_resources.create_time
     *
     * @mbg.generated Tue Apr 24 17:02:34 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.create_time
     *
     * @param createTime the value for sys_resources.create_time
     *
     * @mbg.generated Tue Apr 24 17:02:34 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.update_time
     *
     * @return the value of sys_resources.update_time
     *
     * @mbg.generated Tue Apr 24 17:02:34 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.update_time
     *
     * @param updateTime the value for sys_resources.update_time
     *
     * @mbg.generated Tue Apr 24 17:02:34 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
    
    public Integer getDepartmentType() {
		return departmentType;
	}
    
    public void setDepartmentType(Integer departmentType) {
		this.departmentType = departmentType;
	}
}