package com.bt.om.entity;

import java.util.Date;

public class SysUserRes {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_res.id
     *
     * @mbg.generated Tue Apr 24 17:12:35 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_res.res_id
     *
     * @mbg.generated Tue Apr 24 17:12:35 CST 2018
     */
    private Integer resId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_res.user_id
     *
     * @mbg.generated Tue Apr 24 17:12:35 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_res.type
     *
     * @mbg.generated Tue Apr 24 17:12:35 CST 2018
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_res.create_time
     *
     * @mbg.generated Tue Apr 24 17:12:35 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_res.update_time
     *
     * @mbg.generated Tue Apr 24 17:12:35 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_res.id
     *
     * @return the value of sys_user_res.id
     *
     * @mbg.generated Tue Apr 24 17:12:35 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_res.id
     *
     * @param id the value for sys_user_res.id
     *
     * @mbg.generated Tue Apr 24 17:12:35 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_res.res_id
     *
     * @return the value of sys_user_res.res_id
     *
     * @mbg.generated Tue Apr 24 17:12:35 CST 2018
     */
    public Integer getResId() {
        return resId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_res.res_id
     *
     * @param resId the value for sys_user_res.res_id
     *
     * @mbg.generated Tue Apr 24 17:12:35 CST 2018
     */
    public void setResId(Integer resId) {
        this.resId = resId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_res.user_id
     *
     * @return the value of sys_user_res.user_id
     *
     * @mbg.generated Tue Apr 24 17:12:35 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_res.user_id
     *
     * @param userId the value for sys_user_res.user_id
     *
     * @mbg.generated Tue Apr 24 17:12:35 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_res.type
     *
     * @return the value of sys_user_res.type
     *
     * @mbg.generated Tue Apr 24 17:12:35 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_res.type
     *
     * @param type the value for sys_user_res.type
     *
     * @mbg.generated Tue Apr 24 17:12:35 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_res.create_time
     *
     * @return the value of sys_user_res.create_time
     *
     * @mbg.generated Tue Apr 24 17:12:35 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_res.create_time
     *
     * @param createTime the value for sys_user_res.create_time
     *
     * @mbg.generated Tue Apr 24 17:12:35 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_res.update_time
     *
     * @return the value of sys_user_res.update_time
     *
     * @mbg.generated Tue Apr 24 17:12:35 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_res.update_time
     *
     * @param updateTime the value for sys_user_res.update_time
     *
     * @mbg.generated Tue Apr 24 17:12:35 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}