package com.bt.om.entity;

import java.util.Date;

public class SysUserExecute extends ID {
    /**
	 * 
	 */
	private static final long serialVersionUID = -4120866449013307962L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_execute.id
     *
     * @mbggenerated Tue Jan 23 17:12:28 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_execute.username
     *
     * @mbggenerated Tue Jan 23 17:12:28 CST 2018
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_execute.password
     *
     * @mbggenerated Tue Jan 23 17:12:28 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_execute.realname
     *
     * @mbggenerated Tue Jan 23 17:12:28 CST 2018
     */
    private String realname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_execute.mobile
     *
     * @mbggenerated Tue Jan 23 17:12:28 CST 2018
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_execute.company
     *
     * @mbggenerated Tue Jan 23 17:12:28 CST 2018
     */
    private String company;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_execute.head_img_url
     *
     * @mbggenerated Tue Jan 23 17:12:28 CST 2018
     */
    private String headImgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_execute.usertype
     *
     * @mbggenerated Tue Jan 23 17:12:28 CST 2018
     */
    private Integer usertype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_execute.status
     *
     * @mbggenerated Tue Jan 23 17:12:28 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_execute.province
     *
     * @mbggenerated Tue Jan 23 17:12:28 CST 2018
     */
    private Long province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_execute.city
     *
     * @mbggenerated Tue Jan 23 17:12:28 CST 2018
     */
    private Long city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_execute.region
     *
     * @mbggenerated Tue Jan 23 17:12:28 CST 2018
     */
    private Long region;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_execute.street
     *
     * @mbggenerated Tue Jan 23 17:12:28 CST 2018
     */
    private Long street;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_execute.remark
     *
     * @mbggenerated Tue Jan 23 17:12:28 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_execute.login_ip
     *
     * @mbggenerated Tue Jan 23 17:12:28 CST 2018
     */
    private String loginIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_execute.login_time
     *
     * @mbggenerated Tue Jan 23 17:12:28 CST 2018
     */
    private Date loginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_execute.default_page
     *
     * @mbggenerated Tue Jan 23 17:12:28 CST 2018
     */
    private String defaultPage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_execute.create_time
     *
     * @mbggenerated Tue Jan 23 17:12:28 CST 2018
     */
    
    
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_execute.update_time
     *
     * @mbggenerated Tue Jan 23 17:12:28 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_execute.id
     *
     * @return the value of sys_user_execute.id
     *
     * @mbggenerated Tue Jan 23 17:12:28 CST 2018
     */
    
    private String appSid;
    
    public String getAppSid() {
		return appSid;
	}

	public void setAppSid(String appSid) {
		this.appSid = appSid;
	}
    
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_execute.id
     *
     * @param id the value for sys_user_execute.id
     *
     * @mbggenerated Tue Jan 23 17:12:28 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_execute.username
     *
     * @return the value of sys_user_execute.username
     *
     * @mbggenerated Tue Jan 23 17:12:28 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_execute.username
     *
     * @param username the value for sys_user_execute.username
     *
     * @mbggenerated Tue Jan 23 17:12:28 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_execute.password
     *
     * @return the value of sys_user_execute.password
     *
     * @mbggenerated Tue Jan 23 17:12:28 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_execute.password
     *
     * @param password the value for sys_user_execute.password
     *
     * @mbggenerated Tue Jan 23 17:12:28 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_execute.realname
     *
     * @return the value of sys_user_execute.realname
     *
     * @mbggenerated Tue Jan 23 17:12:28 CST 2018
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_execute.realname
     *
     * @param realname the value for sys_user_execute.realname
     *
     * @mbggenerated Tue Jan 23 17:12:28 CST 2018
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_execute.mobile
     *
     * @return the value of sys_user_execute.mobile
     *
     * @mbggenerated Tue Jan 23 17:12:28 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_execute.mobile
     *
     * @param mobile the value for sys_user_execute.mobile
     *
     * @mbggenerated Tue Jan 23 17:12:28 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_execute.company
     *
     * @return the value of sys_user_execute.company
     *
     * @mbggenerated Tue Jan 23 17:12:28 CST 2018
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_execute.company
     *
     * @param company the value for sys_user_execute.company
     *
     * @mbggenerated Tue Jan 23 17:12:28 CST 2018
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_execute.head_img_url
     *
     * @return the value of sys_user_execute.head_img_url
     *
     * @mbggenerated Tue Jan 23 17:12:28 CST 2018
     */
    public String getHeadImgUrl() {
        return headImgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_execute.head_img_url
     *
     * @param headImgUrl the value for sys_user_execute.head_img_url
     *
     * @mbggenerated Tue Jan 23 17:12:28 CST 2018
     */
    public void setHeadImgUrl(String headImgUrl) {
        this.headImgUrl = headImgUrl == null ? null : headImgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_execute.usertype
     *
     * @return the value of sys_user_execute.usertype
     *
     * @mbggenerated Tue Jan 23 17:12:28 CST 2018
     */
    public Integer getUsertype() {
        return usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_execute.usertype
     *
     * @param usertype the value for sys_user_execute.usertype
     *
     * @mbggenerated Tue Jan 23 17:12:28 CST 2018
     */
    public void setUsertype(Integer usertype) {
        this.usertype = usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_execute.status
     *
     * @return the value of sys_user_execute.status
     *
     * @mbggenerated Tue Jan 23 17:12:28 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_execute.status
     *
     * @param status the value for sys_user_execute.status
     *
     * @mbggenerated Tue Jan 23 17:12:28 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_execute.province
     *
     * @return the value of sys_user_execute.province
     *
     * @mbggenerated Tue Jan 23 17:12:28 CST 2018
     */
    public Long getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_execute.province
     *
     * @param province the value for sys_user_execute.province
     *
     * @mbggenerated Tue Jan 23 17:12:28 CST 2018
     */
    public void setProvince(Long province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_execute.city
     *
     * @return the value of sys_user_execute.city
     *
     * @mbggenerated Tue Jan 23 17:12:28 CST 2018
     */
    public Long getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_execute.city
     *
     * @param city the value for sys_user_execute.city
     *
     * @mbggenerated Tue Jan 23 17:12:28 CST 2018
     */
    public void setCity(Long city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_execute.region
     *
     * @return the value of sys_user_execute.region
     *
     * @mbggenerated Tue Jan 23 17:12:28 CST 2018
     */
    public Long getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_execute.region
     *
     * @param region the value for sys_user_execute.region
     *
     * @mbggenerated Tue Jan 23 17:12:28 CST 2018
     */
    public void setRegion(Long region) {
        this.region = region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_execute.street
     *
     * @return the value of sys_user_execute.street
     *
     * @mbggenerated Tue Jan 23 17:12:28 CST 2018
     */
    public Long getStreet() {
        return street;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_execute.street
     *
     * @param street the value for sys_user_execute.street
     *
     * @mbggenerated Tue Jan 23 17:12:28 CST 2018
     */
    public void setStreet(Long street) {
        this.street = street;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_execute.remark
     *
     * @return the value of sys_user_execute.remark
     *
     * @mbggenerated Tue Jan 23 17:12:28 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_execute.remark
     *
     * @param remark the value for sys_user_execute.remark
     *
     * @mbggenerated Tue Jan 23 17:12:28 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_execute.login_ip
     *
     * @return the value of sys_user_execute.login_ip
     *
     * @mbggenerated Tue Jan 23 17:12:28 CST 2018
     */
    public String getLoginIp() {
        return loginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_execute.login_ip
     *
     * @param loginIp the value for sys_user_execute.login_ip
     *
     * @mbggenerated Tue Jan 23 17:12:28 CST 2018
     */
    public void setLoginIp(String loginIp) {
        this.loginIp = loginIp == null ? null : loginIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_execute.login_time
     *
     * @return the value of sys_user_execute.login_time
     *
     * @mbggenerated Tue Jan 23 17:12:28 CST 2018
     */
    public Date getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_execute.login_time
     *
     * @param loginTime the value for sys_user_execute.login_time
     *
     * @mbggenerated Tue Jan 23 17:12:28 CST 2018
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_execute.default_page
     *
     * @return the value of sys_user_execute.default_page
     *
     * @mbggenerated Tue Jan 23 17:12:28 CST 2018
     */
    public String getDefaultPage() {
        return defaultPage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_execute.default_page
     *
     * @param defaultPage the value for sys_user_execute.default_page
     *
     * @mbggenerated Tue Jan 23 17:12:28 CST 2018
     */
    public void setDefaultPage(String defaultPage) {
        this.defaultPage = defaultPage == null ? null : defaultPage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_execute.create_time
     *
     * @return the value of sys_user_execute.create_time
     *
     * @mbggenerated Tue Jan 23 17:12:28 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_execute.create_time
     *
     * @param createTime the value for sys_user_execute.create_time
     *
     * @mbggenerated Tue Jan 23 17:12:28 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_execute.update_time
     *
     * @return the value of sys_user_execute.update_time
     *
     * @mbggenerated Tue Jan 23 17:12:28 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_execute.update_time
     *
     * @param updateTime the value for sys_user_execute.update_time
     *
     * @mbggenerated Tue Jan 23 17:12:28 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    private Integer operateId;

    public Integer getOperateId() {
        return operateId;
    }

    public void setOperateId(Integer operateId) {
        this.operateId = operateId;
    }
}