package com.bt.om.entity;

import java.util.Date;

public class SysUserDetail extends ID {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_detail.id
     *
     * @mbggenerated Tue Jan 16 19:05:23 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_detail.user_id
     *
     * @mbggenerated Tue Jan 16 19:05:23 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_detail.company_name
     *
     * @mbggenerated Tue Jan 16 19:05:23 CST 2018
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_detail.company_address
     *
     * @mbggenerated Tue Jan 16 19:05:23 CST 2018
     */
    private String companyAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_detail.company_url
     *
     * @mbggenerated Tue Jan 16 19:05:23 CST 2018
     */
    private String companyUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_detail.contacts
     *
     * @mbggenerated Tue Jan 16 19:05:23 CST 2018
     */
    private String contacts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_detail.telephone
     *
     * @mbggenerated Tue Jan 16 19:05:23 CST 2018
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_detail.icp_img_url
     *
     * @mbggenerated Tue Jan 16 19:05:23 CST 2018
     */
    private String icpImgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_detail.idcard_img_url
     *
     * @mbggenerated Tue Jan 16 19:05:23 CST 2018
     */
    private String idcardImgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_detail.business_license
     *
     * @mbggenerated Tue Jan 16 19:05:23 CST 2018
     */
    private String businessLicense;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_detail.create_time
     *
     * @mbggenerated Tue Jan 16 19:05:23 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_detail.update_time
     *
     * @mbggenerated Tue Jan 16 19:05:23 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_detail.id
     *
     * @return the value of sys_user_detail.id
     *
     * @mbggenerated Tue Jan 16 19:05:23 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_detail.id
     *
     * @param id the value for sys_user_detail.id
     *
     * @mbggenerated Tue Jan 16 19:05:23 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_detail.user_id
     *
     * @return the value of sys_user_detail.user_id
     *
     * @mbggenerated Tue Jan 16 19:05:23 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_detail.user_id
     *
     * @param userId the value for sys_user_detail.user_id
     *
     * @mbggenerated Tue Jan 16 19:05:23 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_detail.company_name
     *
     * @return the value of sys_user_detail.company_name
     *
     * @mbggenerated Tue Jan 16 19:05:23 CST 2018
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_detail.company_name
     *
     * @param companyName the value for sys_user_detail.company_name
     *
     * @mbggenerated Tue Jan 16 19:05:23 CST 2018
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_detail.company_address
     *
     * @return the value of sys_user_detail.company_address
     *
     * @mbggenerated Tue Jan 16 19:05:23 CST 2018
     */
    public String getCompanyAddress() {
        return companyAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_detail.company_address
     *
     * @param companyAddress the value for sys_user_detail.company_address
     *
     * @mbggenerated Tue Jan 16 19:05:23 CST 2018
     */
    public void setCompanyAddress(String companyAddress) {
        this.companyAddress = companyAddress == null ? null : companyAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_detail.company_url
     *
     * @return the value of sys_user_detail.company_url
     *
     * @mbggenerated Tue Jan 16 19:05:23 CST 2018
     */
    public String getCompanyUrl() {
        return companyUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_detail.company_url
     *
     * @param companyUrl the value for sys_user_detail.company_url
     *
     * @mbggenerated Tue Jan 16 19:05:23 CST 2018
     */
    public void setCompanyUrl(String companyUrl) {
        this.companyUrl = companyUrl == null ? null : companyUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_detail.contacts
     *
     * @return the value of sys_user_detail.contacts
     *
     * @mbggenerated Tue Jan 16 19:05:23 CST 2018
     */
    public String getContacts() {
        return contacts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_detail.contacts
     *
     * @param contacts the value for sys_user_detail.contacts
     *
     * @mbggenerated Tue Jan 16 19:05:23 CST 2018
     */
    public void setContacts(String contacts) {
        this.contacts = contacts == null ? null : contacts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_detail.telephone
     *
     * @return the value of sys_user_detail.telephone
     *
     * @mbggenerated Tue Jan 16 19:05:23 CST 2018
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_detail.telephone
     *
     * @param telephone the value for sys_user_detail.telephone
     *
     * @mbggenerated Tue Jan 16 19:05:23 CST 2018
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_detail.icp_img_url
     *
     * @return the value of sys_user_detail.icp_img_url
     *
     * @mbggenerated Tue Jan 16 19:05:23 CST 2018
     */
    public String getIcpImgUrl() {
        return icpImgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_detail.icp_img_url
     *
     * @param icpImgUrl the value for sys_user_detail.icp_img_url
     *
     * @mbggenerated Tue Jan 16 19:05:23 CST 2018
     */
    public void setIcpImgUrl(String icpImgUrl) {
        this.icpImgUrl = icpImgUrl == null ? null : icpImgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_detail.idcard_img_url
     *
     * @return the value of sys_user_detail.idcard_img_url
     *
     * @mbggenerated Tue Jan 16 19:05:23 CST 2018
     */
    public String getIdcardImgUrl() {
        return idcardImgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_detail.idcard_img_url
     *
     * @param idcardImgUrl the value for sys_user_detail.idcard_img_url
     *
     * @mbggenerated Tue Jan 16 19:05:23 CST 2018
     */
    public void setIdcardImgUrl(String idcardImgUrl) {
        this.idcardImgUrl = idcardImgUrl == null ? null : idcardImgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_detail.business_license
     *
     * @return the value of sys_user_detail.business_license
     *
     * @mbggenerated Tue Jan 16 19:05:23 CST 2018
     */
    public String getBusinessLicense() {
        return businessLicense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_detail.business_license
     *
     * @param businessLicense the value for sys_user_detail.business_license
     *
     * @mbggenerated Tue Jan 16 19:05:23 CST 2018
     */
    public void setBusinessLicense(String businessLicense) {
        this.businessLicense = businessLicense == null ? null : businessLicense.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_detail.create_time
     *
     * @return the value of sys_user_detail.create_time
     *
     * @mbggenerated Tue Jan 16 19:05:23 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_detail.create_time
     *
     * @param createTime the value for sys_user_detail.create_time
     *
     * @mbggenerated Tue Jan 16 19:05:23 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_detail.update_time
     *
     * @return the value of sys_user_detail.update_time
     *
     * @mbggenerated Tue Jan 16 19:05:23 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_detail.update_time
     *
     * @param updateTime the value for sys_user_detail.update_time
     *
     * @mbggenerated Tue Jan 16 19:05:23 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}