package com.bt.om.entity;

import java.util.Date;

public class SysUserHistory {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user_history.id
	 * @mbg.generated  Thu Jul 12 14:22:58 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user_history.user_id
	 * @mbg.generated  Thu Jul 12 14:22:58 CST 2018
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user_history.login_id
	 * @mbg.generated  Thu Jul 12 14:22:58 CST 2018
	 */
	private Integer loginId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user_history.usertype_old
	 * @mbg.generated  Thu Jul 12 14:22:58 CST 2018
	 */
	private Integer usertypeOld;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user_history.operate_id_old
	 * @mbg.generated  Thu Jul 12 14:22:58 CST 2018
	 */
	private Integer operateIdOld;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user_history.usertype_new
	 * @mbg.generated  Thu Jul 12 14:22:58 CST 2018
	 */
	private Integer usertypeNew;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user_history.operate_id_new
	 * @mbg.generated  Thu Jul 12 14:22:58 CST 2018
	 */
	private Integer operateIdNew;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user_history.create_time
	 * @mbg.generated  Thu Jul 12 14:22:58 CST 2018
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user_history.update_time
	 * @mbg.generated  Thu Jul 12 14:22:58 CST 2018
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user_history.id
	 * @return  the value of sys_user_history.id
	 * @mbg.generated  Thu Jul 12 14:22:58 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user_history.id
	 * @param id  the value for sys_user_history.id
	 * @mbg.generated  Thu Jul 12 14:22:58 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user_history.user_id
	 * @return  the value of sys_user_history.user_id
	 * @mbg.generated  Thu Jul 12 14:22:58 CST 2018
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user_history.user_id
	 * @param userId  the value for sys_user_history.user_id
	 * @mbg.generated  Thu Jul 12 14:22:58 CST 2018
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user_history.login_id
	 * @return  the value of sys_user_history.login_id
	 * @mbg.generated  Thu Jul 12 14:22:58 CST 2018
	 */
	public Integer getLoginId() {
		return loginId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user_history.login_id
	 * @param loginId  the value for sys_user_history.login_id
	 * @mbg.generated  Thu Jul 12 14:22:58 CST 2018
	 */
	public void setLoginId(Integer loginId) {
		this.loginId = loginId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user_history.usertype_old
	 * @return  the value of sys_user_history.usertype_old
	 * @mbg.generated  Thu Jul 12 14:22:58 CST 2018
	 */
	public Integer getUsertypeOld() {
		return usertypeOld;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user_history.usertype_old
	 * @param usertypeOld  the value for sys_user_history.usertype_old
	 * @mbg.generated  Thu Jul 12 14:22:58 CST 2018
	 */
	public void setUsertypeOld(Integer usertypeOld) {
		this.usertypeOld = usertypeOld;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user_history.operate_id_old
	 * @return  the value of sys_user_history.operate_id_old
	 * @mbg.generated  Thu Jul 12 14:22:58 CST 2018
	 */
	public Integer getOperateIdOld() {
		return operateIdOld;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user_history.operate_id_old
	 * @param operateIdOld  the value for sys_user_history.operate_id_old
	 * @mbg.generated  Thu Jul 12 14:22:58 CST 2018
	 */
	public void setOperateIdOld(Integer operateIdOld) {
		this.operateIdOld = operateIdOld;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user_history.usertype_new
	 * @return  the value of sys_user_history.usertype_new
	 * @mbg.generated  Thu Jul 12 14:22:58 CST 2018
	 */
	public Integer getUsertypeNew() {
		return usertypeNew;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user_history.usertype_new
	 * @param usertypeNew  the value for sys_user_history.usertype_new
	 * @mbg.generated  Thu Jul 12 14:22:58 CST 2018
	 */
	public void setUsertypeNew(Integer usertypeNew) {
		this.usertypeNew = usertypeNew;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user_history.operate_id_new
	 * @return  the value of sys_user_history.operate_id_new
	 * @mbg.generated  Thu Jul 12 14:22:58 CST 2018
	 */
	public Integer getOperateIdNew() {
		return operateIdNew;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user_history.operate_id_new
	 * @param operateIdNew  the value for sys_user_history.operate_id_new
	 * @mbg.generated  Thu Jul 12 14:22:58 CST 2018
	 */
	public void setOperateIdNew(Integer operateIdNew) {
		this.operateIdNew = operateIdNew;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user_history.create_time
	 * @return  the value of sys_user_history.create_time
	 * @mbg.generated  Thu Jul 12 14:22:58 CST 2018
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user_history.create_time
	 * @param createTime  the value for sys_user_history.create_time
	 * @mbg.generated  Thu Jul 12 14:22:58 CST 2018
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user_history.update_time
	 * @return  the value of sys_user_history.update_time
	 * @mbg.generated  Thu Jul 12 14:22:58 CST 2018
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user_history.update_time
	 * @param updateTime  the value for sys_user_history.update_time
	 * @mbg.generated  Thu Jul 12 14:22:58 CST 2018
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}