package com.bt.om.entity;

import java.util.Date;

public class User extends ID{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.mobile
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.alipay_account
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    private String alipayAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.alipay_name
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    private String alipayName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.weixin_account
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    private String weixinAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.balance
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    private Double balance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.create_time
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.update_time
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.mobile
     *
     * @return the value of user.mobile
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.mobile
     *
     * @param mobile the value for user.mobile
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.alipay_account
     *
     * @return the value of user.alipay_account
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public String getAlipayAccount() {
        return alipayAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.alipay_account
     *
     * @param alipayAccount the value for user.alipay_account
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public void setAlipayAccount(String alipayAccount) {
        this.alipayAccount = alipayAccount == null ? null : alipayAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.alipay_name
     *
     * @return the value of user.alipay_name
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public String getAlipayName() {
        return alipayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.alipay_name
     *
     * @param alipayName the value for user.alipay_name
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public void setAlipayName(String alipayName) {
        this.alipayName = alipayName == null ? null : alipayName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.weixin_account
     *
     * @return the value of user.weixin_account
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public String getWeixinAccount() {
        return weixinAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.weixin_account
     *
     * @param weixinAccount the value for user.weixin_account
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public void setWeixinAccount(String weixinAccount) {
        this.weixinAccount = weixinAccount == null ? null : weixinAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.balance
     *
     * @return the value of user.balance
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public Double getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.balance
     *
     * @param balance the value for user.balance
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public void setBalance(Double balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.create_time
     *
     * @return the value of user.create_time
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.create_time
     *
     * @param createTime the value for user.create_time
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.update_time
     *
     * @return the value of user.update_time
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.update_time
     *
     * @param updateTime the value for user.update_time
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}