package com.bt.om.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.bt.om.entity.AdActivityAdseat;
import com.bt.om.entity.AdSeatInfo;
import com.bt.om.entity.vo.AdActivityAdseatTaskVo;
import com.bt.om.entity.vo.AdActivityAdseatVo;
import com.bt.om.entity.vo.AdSeatCount;

public interface AdActivityAdseatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_activity_adseat
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_activity_adseat
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    int insert(AdActivityAdseat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_activity_adseat
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    int insertSelective(AdActivityAdseat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_activity_adseat
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    AdActivityAdseat selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_activity_adseat
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    int updateByPrimaryKeySelective(AdActivityAdseat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_activity_adseat
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    int updateByPrimaryKey(AdActivityAdseat record);

    List<AdActivityAdseatVo> selectByActivityId(@Param("activityId") Integer activityId);

    int deleteByActivityId(@Param("activityId") Integer activityId);

    AdActivityAdseatVo selectVoById(@Param("id") Integer id);

    List<AdActivityAdseatVo> selectVoBySeatId(@Param("seatId") Integer seatId);
    List<AdActivityAdseatVo> selectVoBySeatCode(@Param("adSeatCode") String adSeatCode);

    AdActivityAdseat selectByActivityAndSeatId(@Param("activityId") Integer activityId,@Param("seatId") Integer seatId);
    
    List<AdActivityAdseatTaskVo> selectAdActivityAdseatTask(@Param("activityId") Integer activityId);
    List<AdActivityAdseatTaskVo> selectAdSeatTaskReport(@Param("activityId") Integer activityId);
    
    List<AdActivityAdseatVo> selectVoByLonLatTitle(@Param("lon") Double lon, @Param("lat") Double lat, @Param("title") String title);
    List<Integer> selectSeatIdByActivityId(Map<String, Object> searchMap);
    Integer selectCountByAdSeatId(@Param("adSeatId") Integer adSeatId);
    
    List<AdSeatCount> selectActiveActivityCount();
    List<AdSeatCount> selectActiveActivityCount1(Map<String, Object> searchMap);
    List<AdSeatCount> selectActiveActivityCount2(Map<String, Object> searchMap);
    List<AdSeatCount> selectActiveActivityCount3(Map<String, Object> searchMap);
    List<AdSeatCount> selectActiveActivityCount4(Map<String, Object> searchMap);
    
    List<AdActivityAdseatTaskVo> selectAdActivityAdseatTaskReport(@Param("activityId") Integer activityId);
    
    int selectAdActivityAdseatTaskCount(Map<String, Object> searchMap);
    List<AdActivityAdseatTaskVo> selectAdActivityAdseatTask(Map<String, Object> searchMap, RowBounds rowBounds);
    
    List<AdSeatInfo> selectSeatInfoByActivityId(@Param("activityId") Integer activityId);

	List<AdActivityAdseatVo> selectVoByMemo(@Param("memo")String memo);
}