package com.bt.om.mapper;

import java.util.HashMap;
import java.util.List;

import org.apache.ibatis.session.RowBounds;

import com.bt.om.entity.AdApp;

public interface AdAppMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_app
	 * @mbg.generated  Wed May 30 17:27:30 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_app
	 * @mbg.generated  Wed May 30 17:27:30 CST 2018
	 */
	int insert(AdApp record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_app
	 * @mbg.generated  Wed May 30 17:27:30 CST 2018
	 */
	int insertSelective(AdApp record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_app
	 * @mbg.generated  Wed May 30 17:27:30 CST 2018
	 */
	AdApp selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_app
	 * @mbg.generated  Wed May 30 17:27:30 CST 2018
	 */
	int updateByPrimaryKeySelective(AdApp record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_app
	 * @mbg.generated  Wed May 30 17:27:30 CST 2018
	 */
	int updateByPrimaryKey(AdApp record);

	int getPageCount(HashMap<String, Object> searchMap);

	List<?> getPageData(HashMap<String, Object> searchMap, RowBounds rowBounds);

	List<AdApp> getAllAppType();

}
