package com.bt.om.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.bt.om.entity.AdMonitorTaskFeedbackResources;
import com.bt.om.entity.HistoryAdMonitorTaskFeedback;

public interface AdMonitorTaskFeedbackResourcesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_monitor_task_feedback_resources
     *
     * @mbg.generated Wed Aug 08 10:35:35 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_monitor_task_feedback_resources
     *
     * @mbg.generated Wed Aug 08 10:35:35 CST 2018
     */
    int insert(AdMonitorTaskFeedbackResources record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_monitor_task_feedback_resources
     *
     * @mbg.generated Wed Aug 08 10:35:35 CST 2018
     */
    int insertSelective(AdMonitorTaskFeedbackResources record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_monitor_task_feedback_resources
     *
     * @mbg.generated Wed Aug 08 10:35:35 CST 2018
     */
    AdMonitorTaskFeedbackResources selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_monitor_task_feedback_resources
     *
     * @mbg.generated Wed Aug 08 10:35:35 CST 2018
     */
    int updateByPrimaryKeySelective(AdMonitorTaskFeedbackResources record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_monitor_task_feedback_resources
     *
     * @mbg.generated Wed Aug 08 10:35:35 CST 2018
     */
    int updateByPrimaryKey(AdMonitorTaskFeedbackResources record);
    
    List<AdMonitorTaskFeedbackResources> selectByMonitorTaskFeedbackId(Integer monitorTaskFeedbackId);

	int updatePicUrl(Map<String, Object> searchMap);

	int selectCountByMonitorTaskFeedbackId(Integer monitorTaskFeedbackId);

	int insertBatch(@Param("pics")List<AdMonitorTaskFeedbackResources> resources);
	
	List<String> selectPicUrlByMonitorTaskFeedbackId(Integer monitorTaskFeedbackId);
	/**
	 * 修改监测任务驳回图片状态到审核中
	 */
	int updateRejectPicStatusByTaskFeedbackId(Integer monitorTaskFeedbackId);

	int updatePicStatusByBackId(@Param("backId")Integer backId, @Param("status")Integer status);

	int deleteByBackIds(@Param("backs")List<HistoryAdMonitorTaskFeedback> adMonitorTaskFeedbacks);
	
}