package com.bt.om.mapper;

import java.util.HashMap;
import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.bt.om.entity.AdPoint;

public interface AdPointMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_point
     *
     * @mbg.generated Thu May 31 11:11:28 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_point
     *
     * @mbg.generated Thu May 31 11:11:28 CST 2018
     */
    int insert(AdPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_point
     *
     * @mbg.generated Thu May 31 11:11:28 CST 2018
     */
    int insertSelective(AdPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_point
     *
     * @mbg.generated Thu May 31 11:11:28 CST 2018
     */
    AdPoint selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_point
     *
     * @mbg.generated Thu May 31 11:11:28 CST 2018
     */
    int updateByPrimaryKeySelective(AdPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_point
     *
     * @mbg.generated Thu May 31 11:11:28 CST 2018
     */
    int updateByPrimaryKey(AdPoint record);

    /**
     * 通过type找到积分设置明细
     * */
	AdPoint selectByPointType(@Param("type")int type);

	/**
	 * 查询所有满足条件的数据条数
	 * */
	int getPageCount(HashMap<String, Object> searchMap);

	/**
	 * 查询所有满足条件的数据
	 * */
	List<?> getPageData(HashMap<String, Object> searchMap, RowBounds rowBounds);
}