package com.bt.om.mapper;

import org.apache.ibatis.annotations.Param;

import com.bt.om.entity.AdPoint;

public interface AdPointMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_point
     *
     * @mbg.generated Thu May 31 11:11:28 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_point
     *
     * @mbg.generated Thu May 31 11:11:28 CST 2018
     */
    int insert(AdPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_point
     *
     * @mbg.generated Thu May 31 11:11:28 CST 2018
     */
    int insertSelective(AdPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_point
     *
     * @mbg.generated Thu May 31 11:11:28 CST 2018
     */
    AdPoint selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_point
     *
     * @mbg.generated Thu May 31 11:11:28 CST 2018
     */
    int updateByPrimaryKeySelective(AdPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_point
     *
     * @mbg.generated Thu May 31 11:11:28 CST 2018
     */
    int updateByPrimaryKey(AdPoint record);

	AdPoint selectByPointType(@Param("type")int type);
}