package com.bt.om.mapper;

import com.bt.om.entity.AdSms;

public interface AdSmsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_sms
     *
     * @mbg.generated Sun Apr 08 15:33:42 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_sms
     *
     * @mbg.generated Sun Apr 08 15:33:42 CST 2018
     */
    int insert(AdSms record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_sms
     *
     * @mbg.generated Sun Apr 08 15:33:42 CST 2018
     */
    int insertSelective(AdSms record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_sms
     *
     * @mbg.generated Sun Apr 08 15:33:42 CST 2018
     */
    AdSms selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_sms
     *
     * @mbg.generated Sun Apr 08 15:33:42 CST 2018
     */
    int updateByPrimaryKeySelective(AdSms record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_sms
     *
     * @mbg.generated Sun Apr 08 15:33:42 CST 2018
     */
    int updateByPrimaryKey(AdSms record);
}