package com.bt.om.mapper;

import com.bt.om.entity.AdUserPoint;

public interface AdUserPointMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_user_point
     *
     * @mbg.generated Thu May 31 11:25:13 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_user_point
     *
     * @mbg.generated Thu May 31 11:25:13 CST 2018
     */
    int insert(AdUserPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_user_point
     *
     * @mbg.generated Thu May 31 11:25:13 CST 2018
     */
    int insertSelective(AdUserPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_user_point
     *
     * @mbg.generated Thu May 31 11:25:13 CST 2018
     */
    AdUserPoint selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_user_point
     *
     * @mbg.generated Thu May 31 11:25:13 CST 2018
     */
    int updateByPrimaryKeySelective(AdUserPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_user_point
     *
     * @mbg.generated Thu May 31 11:25:13 CST 2018
     */
    int updateByPrimaryKey(AdUserPoint record);
}