package com.bt.om.mapper;

import java.util.HashMap;
import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.bt.om.entity.AdUserMessage;

public interface AdUserMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_message
     *
     * @mbg.generated Tue Jun 19 15:09:44 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_message
     *
     * @mbg.generated Tue Jun 19 15:09:44 CST 2018
     */
    int insert(AdUserMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_message
     *
     * @mbg.generated Tue Jun 19 15:09:44 CST 2018
     */
    int insertSelective(AdUserMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_message
     *
     * @mbg.generated Tue Jun 19 15:09:44 CST 2018
     */
    AdUserMessage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_message
     *
     * @mbg.generated Tue Jun 19 15:09:44 CST 2018
     */
    int updateByPrimaryKeySelective(AdUserMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_message
     *
     * @mbg.generated Tue Jun 19 15:09:44 CST 2018
     */
    int updateByPrimaryKey(AdUserMessage record);

	int getPageCount(HashMap<String, Object> searchMap);

	List<?> getPageData(HashMap<String, Object> searchMap, RowBounds rowBounds);

	void insertMessage(@Param("messages")List<AdUserMessage> message);

}