package com.bt.om.mapper;

import java.util.HashMap;
import java.util.List;

import org.apache.ibatis.session.RowBounds;

import com.bt.om.entity.AdUserPoint;

public interface AdUserPointMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_user_point
     *
     * @mbg.generated Thu May 31 11:25:13 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_user_point
     *
     * @mbg.generated Thu May 31 11:25:13 CST 2018
     */
    int insert(AdUserPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_user_point
     *
     * @mbg.generated Thu May 31 11:25:13 CST 2018
     */
    int insertSelective(AdUserPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_user_point
     *
     * @mbg.generated Thu May 31 11:25:13 CST 2018
     */
    AdUserPoint selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_user_point
     *
     * @mbg.generated Thu May 31 11:25:13 CST 2018
     */
    int updateByPrimaryKeySelective(AdUserPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_user_point
     *
     * @mbg.generated Thu May 31 11:25:13 CST 2018
     */
    int updateByPrimaryKey(AdUserPoint record);

	int getPageCount(HashMap<String, Object> searchMap);

	List<?> getPageData(HashMap<String, Object> searchMap, RowBounds rowBounds);

	//通过用户id查找该用户的所有积分数据
	List<AdUserPoint> getListById(Integer userId);

	Integer getPointCountById(Integer userId);
}