package com.bt.om.mapper;

import com.bt.om.entity.AdVersion;

public interface AdVersionMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_version
	 * @mbg.generated  Fri Jul 27 11:08:45 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_version
	 * @mbg.generated  Fri Jul 27 11:08:45 CST 2018
	 */
	int insert(AdVersion record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_version
	 * @mbg.generated  Fri Jul 27 11:08:45 CST 2018
	 */
	int insertSelective(AdVersion record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_version
	 * @mbg.generated  Fri Jul 27 11:08:45 CST 2018
	 */
	AdVersion selectByPrimaryKey(Integer id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_version
	 * @mbg.generated  Fri Jul 27 11:08:45 CST 2018
	 */
	int updateByPrimaryKeySelective(AdVersion record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_version
	 * @mbg.generated  Fri Jul 27 11:08:45 CST 2018
	 */
	int updateByPrimaryKey(AdVersion record);
	AdVersion selectLatestForceUpdateRecord();
    AdVersion selectLatestRecord();
}