package com.bt.om.mapper;

import com.bt.om.entity.DrawCash;

public interface DrawCashMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_cash
     *
     * @mbg.generated Wed Feb 07 19:58:30 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_cash
     *
     * @mbg.generated Wed Feb 07 19:58:30 CST 2018
     */
    int insert(DrawCash record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_cash
     *
     * @mbg.generated Wed Feb 07 19:58:30 CST 2018
     */
    int insertSelective(DrawCash record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_cash
     *
     * @mbg.generated Wed Feb 07 19:58:30 CST 2018
     */
    DrawCash selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_cash
     *
     * @mbg.generated Wed Feb 07 19:58:30 CST 2018
     */
    int updateByPrimaryKeySelective(DrawCash record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_cash
     *
     * @mbg.generated Wed Feb 07 19:58:30 CST 2018
     */
    int updateByPrimaryKey(DrawCash record);
}