package com.bt.om.mapper;

import com.bt.om.entity.AdJiucuoTask;
import com.bt.om.entity.AdMonitorTask;
import com.bt.om.entity.HistoryAdJiucuoTask;
import com.bt.om.entity.vo.AdJiucuoTaskMobileVo;
import com.bt.om.entity.vo.AdJiucuoTaskVo;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

public interface HistoryAdJiucuoTaskMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_jiucuo_task
     *
     * @mbggenerated Sun Jan 21 14:46:36 CST 2018
     */
    int insert(AdJiucuoTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_jiucuo_task
     *
     * @mbggenerated Sun Jan 21 14:46:36 CST 2018
     */
    int insertSelective(HistoryAdJiucuoTask record);

    int getPageCount(Map<String, Object> searchMap);

    List<AdJiucuoTaskVo> getPageData(Map<String, Object> searchMap, RowBounds rowBounds);

    AdJiucuoTaskVo selectVoByPrimaryKey(HashMap<String, Object> searchMap);

	int insertBatch(@Param("tableName") String tableName,@Param("adJiucuoTasks") List<HistoryAdJiucuoTask> adJiucuoTasks);
	
}