package com.bt.om.mapper;

import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.bt.om.entity.AdActivity;
import com.bt.om.entity.HistoryAdActivity;
import com.bt.om.entity.vo.ActivityMobileReportVo;
import com.bt.om.entity.vo.AdActivityVo;
import com.bt.om.entity.vo.AdActivityVo2;
import com.bt.om.vo.web.SearchDataVo;

public interface HistoryAdActivityMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_activity
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    int insertSelective(AdActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_activity
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */
    AdActivity selectByPrimaryKey(Map<String, Object> searchMap);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_activity
     *
     * @mbggenerated Thu Jan 18 14:25:00 CST 2018
     */

    int getPageCount(Map<String, Object> searchMap);

    List<AdActivityVo2> getPageData(Map<String, Object> searchMap, RowBounds rowBounds);

    AdActivityVo selectVoByPrimaryKey(HashMap<String, Object> searchMap);
}