package com.bt.om.mapper;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.bt.om.entity.AdJiucuoTaskFeedback;
import com.bt.om.entity.HistoryAdJiucuoTask;
import com.bt.om.entity.HistoryAdJiucuoTaskFeedback;

public interface HistoryAdJiucuoTaskFeedbackMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_jiucuo_task_feedback
     *
     * @mbggenerated Sun Jan 21 14:59:02 CST 2018
     */
    int insertSelective(HistoryAdJiucuoTaskFeedback record);
    
    AdJiucuoTaskFeedback selectByTaskId(HashMap<String, Object> searchMap);

	int insertBatch(@Param("tableName") String tableName,@Param("adJiucuoTaskFeedbacks") List<HistoryAdJiucuoTaskFeedback> adJiucuoTaskFeedbacks);

}