package com.bt.om.mapper;

import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.bt.om.entity.AdMonitorTask;
import com.bt.om.entity.AdSeatInfo;
import com.bt.om.entity.HistoryAdMonitorTask;
import com.bt.om.entity.vo.AdMonitorTaskMobileVo;
import com.bt.om.entity.vo.AdMonitorTaskVo;
import com.bt.om.entity.vo.AllAdMonitorTaskVo;
import com.bt.om.entity.vo.PictureVo;
import com.bt.om.entity.vo.TaskAdSeat;
import com.bt.om.vo.web.SearchDataVo;

public interface HistoryAdMonitorTaskMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table ad_monitor_task
	 *
	 * @mbggenerated Sat Jan 20 10:48:02 CST 2018
	 */
	int insertSelective(HistoryAdMonitorTask record);

	int getPageCount(Map<String, Object> searchMap);

    List<AdMonitorTaskVo> getPageData(Map<String, Object> searchMap, RowBounds rowBounds);

	/**
	 * 获取监测任务详情
	 * 
	 * @param searchMap
	 * @return 返回监测任务详情
	 */
	AdMonitorTaskVo getTaskDetails(HashMap<String, Object> searchMap);

	/**
	 * 获取提交详情
	 * 
	 * @param searchMap
	 * @return 返回任务提交详情情况
	 */
	List<AdMonitorTaskVo> getSubmitDetails(HashMap<String, Object> searchMap);

	/**
	 * 根据父id和父类型查询子任务和有效提交列表，放在详情里
	 **/
	List<AdMonitorTaskVo> selectVoByParent(HashMap<String, Object> searchMap);

	List<AdMonitorTask> getAllTasksByActivityId(HashMap<String, Object> searchMap);

	List<AdMonitorTask> newSelectLatestMonitorTaskIds(Map<String, Object> searchMap);

	int insertBatch(@Param("tableName") String tableName,@Param("adMonitorTasks")  List<HistoryAdMonitorTask> adMonitorTasks);

	List<AdMonitorTask> getAllTaskTypesByActivityIdReportTime(Map<String, Object> searchMap);

	List<AdMonitorTaskVo> selectMonitorTaskIdsByActicityId(Map<String, Object> searchMap);
}