package com.bt.om.mapper;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.bt.om.entity.AdMonitorTaskFeedback;
import com.bt.om.entity.HistoryAdMonitorTaskFeedback;

public interface HistoryAdMonitorTaskFeedbackMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_monitor_task_feedback
     *
     * @mbggenerated Wed Jan 24 17:01:09 CST 2018
     */
    int insertSelective(HistoryAdMonitorTaskFeedback record);
    
    List<AdMonitorTaskFeedback> selectByActivity(@Param("tableName") String tableName,@Param("monitorTaskIds") List<Integer> monitorTaskIds);

	int insertBatch(@Param("tableName") String tableName,@Param("adMonitorTaskFeedbacks") List<HistoryAdMonitorTaskFeedback> adMonitorTaskFeedbacks);

}