package com.bt.om.mapper;

import com.bt.om.entity.SysOrder;

public interface SysOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_order
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_order
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    int insert(SysOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_order
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    int insertSelective(SysOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_order
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    SysOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_order
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    int updateByPrimaryKeySelective(SysOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_order
     *
     * @mbg.generated Wed Feb 07 20:04:57 CST 2018
     */
    int updateByPrimaryKey(SysOrder record);
}