package com.bt.om.mapper;

import com.bt.om.entity.SysUserDetail;

public interface SysUserDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_detail
     *
     * @mbggenerated Tue Jan 16 19:05:23 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_detail
     *
     * @mbggenerated Tue Jan 16 19:05:23 CST 2018
     */
    int insert(SysUserDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_detail
     *
     * @mbggenerated Tue Jan 16 19:05:23 CST 2018
     */
    int insertSelective(SysUserDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_detail
     *
     * @mbggenerated Tue Jan 16 19:05:23 CST 2018
     */
    SysUserDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_detail
     *
     * @mbggenerated Tue Jan 16 19:05:23 CST 2018
     */
    int updateByPrimaryKeySelective(SysUserDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_detail
     *
     * @mbggenerated Tue Jan 16 19:05:23 CST 2018
     */
    int updateByPrimaryKey(SysUserDetail record);
}