package com.bt.om.mapper;

import java.util.HashMap;
import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.bt.om.entity.SysUserHistory;

public interface SysUserHistoryMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user_history
	 * @mbg.generated  Thu Jul 12 14:22:58 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user_history
	 * @mbg.generated  Thu Jul 12 14:22:58 CST 2018
	 */
	int insert(SysUserHistory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user_history
	 * @mbg.generated  Thu Jul 12 14:22:58 CST 2018
	 */
	int insertSelective(SysUserHistory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user_history
	 * @mbg.generated  Thu Jul 12 14:22:58 CST 2018
	 */
	SysUserHistory selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user_history
	 * @mbg.generated  Thu Jul 12 14:22:58 CST 2018
	 */
	int updateByPrimaryKeySelective(SysUserHistory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user_history
	 * @mbg.generated  Thu Jul 12 14:22:58 CST 2018
	 */
	int updateByPrimaryKey(SysUserHistory record);

	int getPageCount(HashMap<String, Object> searchMap);

	List<?> getPageData(HashMap<String, Object> searchMap, RowBounds rowBounds);

}